// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"path"
	"reflect"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxr/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type ClassMapTraffic struct {
	Device                         types.String                                 `tfsdk:"device"`
	Id                             types.String                                 `tfsdk:"id"`
	ClassMapName                   types.String                                 `tfsdk:"class_map_name"`
	MatchAll                       types.Bool                                   `tfsdk:"match_all"`
	MatchAny                       types.Bool                                   `tfsdk:"match_any"`
	Description                    types.String                                 `tfsdk:"description"`
	MatchAccessGroupIpv4           types.List                                   `tfsdk:"match_access_group_ipv4"`
	MatchAccessGroupIpv6           types.List                                   `tfsdk:"match_access_group_ipv6"`
	MatchCos                       types.List                                   `tfsdk:"match_cos"`
	MatchCosInner                  types.List                                   `tfsdk:"match_cos_inner"`
	MatchDestinationAddressIpv4    []ClassMapTrafficMatchDestinationAddressIpv4 `tfsdk:"match_destination_address_ipv4"`
	MatchDestinationAddressIpv6    []ClassMapTrafficMatchDestinationAddressIpv6 `tfsdk:"match_destination_address_ipv6"`
	MatchDestinationMac            types.String                                 `tfsdk:"match_destination_mac"`
	MatchDestinationPort           types.List                                   `tfsdk:"match_destination_port"`
	MatchDscp                      types.List                                   `tfsdk:"match_dscp"`
	MatchDscpIpv4                  types.List                                   `tfsdk:"match_dscp_ipv4"`
	MatchDscpIpv6                  types.List                                   `tfsdk:"match_dscp_ipv6"`
	MatchEthertype                 types.List                                   `tfsdk:"match_ethertype"`
	MatchFlowTag                   types.List                                   `tfsdk:"match_flow_tag"`
	MatchFragmentTypeDontFragment  types.Bool                                   `tfsdk:"match_fragment_type_dont_fragment"`
	MatchFragmentTypeFirstFragment types.Bool                                   `tfsdk:"match_fragment_type_first_fragment"`
	MatchFragmentTypeIsFragment    types.Bool                                   `tfsdk:"match_fragment_type_is_fragment"`
	MatchFragmentTypeLastFragment  types.Bool                                   `tfsdk:"match_fragment_type_last_fragment"`
	MatchIpv4IcmpCode              types.List                                   `tfsdk:"match_ipv4_icmp_code"`
	MatchIpv4IcmpType              types.List                                   `tfsdk:"match_ipv4_icmp_type"`
	MatchIpv6IcmpCode              types.List                                   `tfsdk:"match_ipv6_icmp_code"`
	MatchIpv6IcmpType              types.List                                   `tfsdk:"match_ipv6_icmp_type"`
	MatchMplsExperimentalTopmost   types.List                                   `tfsdk:"match_mpls_experimental_topmost"`
	MatchPacketLength              types.List                                   `tfsdk:"match_packet_length"`
	MatchPrecedence                types.List                                   `tfsdk:"match_precedence"`
	MatchPrecedenceIpv4            types.List                                   `tfsdk:"match_precedence_ipv4"`
	MatchPrecedenceIpv6            types.List                                   `tfsdk:"match_precedence_ipv6"`
	MatchProtocol                  types.List                                   `tfsdk:"match_protocol"`
	MatchSourceAddressIpv4         []ClassMapTrafficMatchSourceAddressIpv4      `tfsdk:"match_source_address_ipv4"`
	MatchSourceAddressIpv6         []ClassMapTrafficMatchSourceAddressIpv6      `tfsdk:"match_source_address_ipv6"`
	MatchSourceMac                 types.String                                 `tfsdk:"match_source_mac"`
	MatchSourcePort                types.List                                   `tfsdk:"match_source_port"`
	MatchTcpFlag                   types.Int64                                  `tfsdk:"match_tcp_flag"`
	MatchTcpFlagAny                types.Bool                                   `tfsdk:"match_tcp_flag_any"`
	MatchVlan                      types.List                                   `tfsdk:"match_vlan"`
	MatchVlanInner                 types.List                                   `tfsdk:"match_vlan_inner"`
}

type ClassMapTrafficData struct {
	Device                         types.String                                 `tfsdk:"device"`
	Id                             types.String                                 `tfsdk:"id"`
	ClassMapName                   types.String                                 `tfsdk:"class_map_name"`
	MatchAll                       types.Bool                                   `tfsdk:"match_all"`
	MatchAny                       types.Bool                                   `tfsdk:"match_any"`
	Description                    types.String                                 `tfsdk:"description"`
	MatchAccessGroupIpv4           types.List                                   `tfsdk:"match_access_group_ipv4"`
	MatchAccessGroupIpv6           types.List                                   `tfsdk:"match_access_group_ipv6"`
	MatchCos                       types.List                                   `tfsdk:"match_cos"`
	MatchCosInner                  types.List                                   `tfsdk:"match_cos_inner"`
	MatchDestinationAddressIpv4    []ClassMapTrafficMatchDestinationAddressIpv4 `tfsdk:"match_destination_address_ipv4"`
	MatchDestinationAddressIpv6    []ClassMapTrafficMatchDestinationAddressIpv6 `tfsdk:"match_destination_address_ipv6"`
	MatchDestinationMac            types.String                                 `tfsdk:"match_destination_mac"`
	MatchDestinationPort           types.List                                   `tfsdk:"match_destination_port"`
	MatchDscp                      types.List                                   `tfsdk:"match_dscp"`
	MatchDscpIpv4                  types.List                                   `tfsdk:"match_dscp_ipv4"`
	MatchDscpIpv6                  types.List                                   `tfsdk:"match_dscp_ipv6"`
	MatchEthertype                 types.List                                   `tfsdk:"match_ethertype"`
	MatchFlowTag                   types.List                                   `tfsdk:"match_flow_tag"`
	MatchFragmentTypeDontFragment  types.Bool                                   `tfsdk:"match_fragment_type_dont_fragment"`
	MatchFragmentTypeFirstFragment types.Bool                                   `tfsdk:"match_fragment_type_first_fragment"`
	MatchFragmentTypeIsFragment    types.Bool                                   `tfsdk:"match_fragment_type_is_fragment"`
	MatchFragmentTypeLastFragment  types.Bool                                   `tfsdk:"match_fragment_type_last_fragment"`
	MatchIpv4IcmpCode              types.List                                   `tfsdk:"match_ipv4_icmp_code"`
	MatchIpv4IcmpType              types.List                                   `tfsdk:"match_ipv4_icmp_type"`
	MatchIpv6IcmpCode              types.List                                   `tfsdk:"match_ipv6_icmp_code"`
	MatchIpv6IcmpType              types.List                                   `tfsdk:"match_ipv6_icmp_type"`
	MatchMplsExperimentalTopmost   types.List                                   `tfsdk:"match_mpls_experimental_topmost"`
	MatchPacketLength              types.List                                   `tfsdk:"match_packet_length"`
	MatchPrecedence                types.List                                   `tfsdk:"match_precedence"`
	MatchPrecedenceIpv4            types.List                                   `tfsdk:"match_precedence_ipv4"`
	MatchPrecedenceIpv6            types.List                                   `tfsdk:"match_precedence_ipv6"`
	MatchProtocol                  types.List                                   `tfsdk:"match_protocol"`
	MatchSourceAddressIpv4         []ClassMapTrafficMatchSourceAddressIpv4      `tfsdk:"match_source_address_ipv4"`
	MatchSourceAddressIpv6         []ClassMapTrafficMatchSourceAddressIpv6      `tfsdk:"match_source_address_ipv6"`
	MatchSourceMac                 types.String                                 `tfsdk:"match_source_mac"`
	MatchSourcePort                types.List                                   `tfsdk:"match_source_port"`
	MatchTcpFlag                   types.Int64                                  `tfsdk:"match_tcp_flag"`
	MatchTcpFlagAny                types.Bool                                   `tfsdk:"match_tcp_flag_any"`
	MatchVlan                      types.List                                   `tfsdk:"match_vlan"`
	MatchVlanInner                 types.List                                   `tfsdk:"match_vlan_inner"`
}
type ClassMapTrafficMatchDestinationAddressIpv4 struct {
	Address types.String `tfsdk:"address"`
	Netmask types.String `tfsdk:"netmask"`
}
type ClassMapTrafficMatchDestinationAddressIpv6 struct {
	Address      types.String `tfsdk:"address"`
	PrefixLength types.Int64  `tfsdk:"prefix_length"`
}
type ClassMapTrafficMatchSourceAddressIpv4 struct {
	Address types.String `tfsdk:"address"`
	Netmask types.String `tfsdk:"netmask"`
}
type ClassMapTrafficMatchSourceAddressIpv6 struct {
	Address      types.String `tfsdk:"address"`
	PrefixLength types.Int64  `tfsdk:"prefix_length"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data ClassMapTraffic) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-policymap-classmap-cfg:/class-map/type/traffic[class-map-name=%s]", data.ClassMapName.ValueString())
}

func (data ClassMapTrafficData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-policymap-classmap-cfg:/class-map/type/traffic[class-map-name=%s]", data.ClassMapName.ValueString())
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data ClassMapTraffic) toBody(ctx context.Context, providerVersion string) string {
	body := "{}"
	if !data.ClassMapName.IsNull() && !data.ClassMapName.IsUnknown() {
		body, _ = sjson.Set(body, "class-map-name", data.ClassMapName.ValueString())
	}
	if !data.MatchAll.IsNull() && !data.MatchAll.IsUnknown() {
		if data.MatchAll.ValueBool() {
			body, _ = sjson.Set(body, "match-all", map[string]string{})
		}
	}
	if !data.MatchAny.IsNull() && !data.MatchAny.IsUnknown() {
		if data.MatchAny.ValueBool() {
			body, _ = sjson.Set(body, "match-any", map[string]string{})
		}
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body, _ = sjson.Set(body, "description", data.Description.ValueString())
	}
	if !data.MatchAccessGroupIpv4.IsNull() && !data.MatchAccessGroupIpv4.IsUnknown() {
		var values []string
		data.MatchAccessGroupIpv4.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.access-group.ipv4", values)
	}
	if !data.MatchAccessGroupIpv6.IsNull() && !data.MatchAccessGroupIpv6.IsUnknown() {
		var values []string
		data.MatchAccessGroupIpv6.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.access-group.ipv6", values)
	}
	if !data.MatchCos.IsNull() && !data.MatchCos.IsUnknown() {
		var values []int
		data.MatchCos.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.cos.value", values)
	}
	if !data.MatchCosInner.IsNull() && !data.MatchCosInner.IsUnknown() {
		var values []int
		data.MatchCosInner.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.cos-inner.value", values)
	}
	if !data.MatchDestinationMac.IsNull() && !data.MatchDestinationMac.IsUnknown() {
		body, _ = sjson.Set(body, "match.destination-address.mac", data.MatchDestinationMac.ValueString())
	}
	if !data.MatchDestinationPort.IsNull() && !data.MatchDestinationPort.IsUnknown() {
		var values []string
		data.MatchDestinationPort.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.destination-port.port-number", values)
	}
	if !data.MatchDscp.IsNull() && !data.MatchDscp.IsUnknown() {
		var values []string
		data.MatchDscp.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.dscp.value", values)
	}
	if !data.MatchDscpIpv4.IsNull() && !data.MatchDscpIpv4.IsUnknown() {
		var values []string
		data.MatchDscpIpv4.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.dscp-ipv4.value", values)
	}
	if !data.MatchDscpIpv6.IsNull() && !data.MatchDscpIpv6.IsUnknown() {
		var values []string
		data.MatchDscpIpv6.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.dscp-ipv6.value", values)
	}
	if !data.MatchEthertype.IsNull() && !data.MatchEthertype.IsUnknown() {
		var values []string
		data.MatchEthertype.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.ethertype.value", values)
	}
	if !data.MatchFlowTag.IsNull() && !data.MatchFlowTag.IsUnknown() {
		var values []string
		data.MatchFlowTag.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.flow-tag.tag-number", values)
	}
	if !data.MatchFragmentTypeDontFragment.IsNull() && !data.MatchFragmentTypeDontFragment.IsUnknown() {
		if data.MatchFragmentTypeDontFragment.ValueBool() {
			body, _ = sjson.Set(body, "match.fragment-type.dont-fragment", map[string]string{})
		}
	}
	if !data.MatchFragmentTypeFirstFragment.IsNull() && !data.MatchFragmentTypeFirstFragment.IsUnknown() {
		if data.MatchFragmentTypeFirstFragment.ValueBool() {
			body, _ = sjson.Set(body, "match.fragment-type.first-fragment", map[string]string{})
		}
	}
	if !data.MatchFragmentTypeIsFragment.IsNull() && !data.MatchFragmentTypeIsFragment.IsUnknown() {
		if data.MatchFragmentTypeIsFragment.ValueBool() {
			body, _ = sjson.Set(body, "match.fragment-type.is-fragment", map[string]string{})
		}
	}
	if !data.MatchFragmentTypeLastFragment.IsNull() && !data.MatchFragmentTypeLastFragment.IsUnknown() {
		if data.MatchFragmentTypeLastFragment.ValueBool() {
			body, _ = sjson.Set(body, "match.fragment-type.last-fragment", map[string]string{})
		}
	}
	if !data.MatchIpv4IcmpCode.IsNull() && !data.MatchIpv4IcmpCode.IsUnknown() {
		var values []string
		data.MatchIpv4IcmpCode.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.ipv4.icmp-code.value", values)
	}
	if !data.MatchIpv4IcmpType.IsNull() && !data.MatchIpv4IcmpType.IsUnknown() {
		var values []string
		data.MatchIpv4IcmpType.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.ipv4.icmp-type.value", values)
	}
	if !data.MatchIpv6IcmpCode.IsNull() && !data.MatchIpv6IcmpCode.IsUnknown() {
		var values []string
		data.MatchIpv6IcmpCode.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.ipv6.icmp-code.value", values)
	}
	if !data.MatchIpv6IcmpType.IsNull() && !data.MatchIpv6IcmpType.IsUnknown() {
		var values []string
		data.MatchIpv6IcmpType.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.ipv6.icmp-type.value", values)
	}
	if !data.MatchMplsExperimentalTopmost.IsNull() && !data.MatchMplsExperimentalTopmost.IsUnknown() {
		var values []int
		data.MatchMplsExperimentalTopmost.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.mpls.experimental.topmost.label", values)
	}
	if !data.MatchPacketLength.IsNull() && !data.MatchPacketLength.IsUnknown() {
		var values []string
		data.MatchPacketLength.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.packet.length.value", values)
	}
	if !data.MatchPrecedence.IsNull() && !data.MatchPrecedence.IsUnknown() {
		var values []string
		data.MatchPrecedence.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.precedence.value", values)
	}
	if !data.MatchPrecedenceIpv4.IsNull() && !data.MatchPrecedenceIpv4.IsUnknown() {
		var values []string
		data.MatchPrecedenceIpv4.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.precedence-ipv4.value", values)
	}
	if !data.MatchPrecedenceIpv6.IsNull() && !data.MatchPrecedenceIpv6.IsUnknown() {
		var values []string
		data.MatchPrecedenceIpv6.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.precedence-ipv6.value", values)
	}
	if !data.MatchProtocol.IsNull() && !data.MatchProtocol.IsUnknown() {
		var values []string
		data.MatchProtocol.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.protocol.number", values)
	}
	if !data.MatchSourceMac.IsNull() && !data.MatchSourceMac.IsUnknown() {
		body, _ = sjson.Set(body, "match.source-address.mac", data.MatchSourceMac.ValueString())
	}
	if !data.MatchSourcePort.IsNull() && !data.MatchSourcePort.IsUnknown() {
		var values []string
		data.MatchSourcePort.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.source-port.number", values)
	}
	if !data.MatchTcpFlag.IsNull() && !data.MatchTcpFlag.IsUnknown() {
		body, _ = sjson.Set(body, "match.tcp-flag.value", strconv.FormatInt(data.MatchTcpFlag.ValueInt64(), 10))
	}
	if !data.MatchTcpFlagAny.IsNull() && !data.MatchTcpFlagAny.IsUnknown() {
		if data.MatchTcpFlagAny.ValueBool() {
			body, _ = sjson.Set(body, "match.tcp-flag.any", map[string]string{})
		}
	}
	if !data.MatchVlan.IsNull() && !data.MatchVlan.IsUnknown() {
		var values []string
		data.MatchVlan.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.vlan.vlan-id", values)
	}
	if !data.MatchVlanInner.IsNull() && !data.MatchVlanInner.IsUnknown() {
		var values []string
		data.MatchVlanInner.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "match.vlan-inner.vlan-id", values)
	}
	if len(data.MatchDestinationAddressIpv4) > 0 {
		body, _ = sjson.Set(body, "match.destination-address.ipv4.address-prefix", []interface{}{})
		for index, item := range data.MatchDestinationAddressIpv4 {
			if !item.Address.IsNull() && !item.Address.IsUnknown() {
				body, _ = sjson.Set(body, "match.destination-address.ipv4.address-prefix"+"."+strconv.Itoa(index)+"."+"address", item.Address.ValueString())
			}
			if !item.Netmask.IsNull() && !item.Netmask.IsUnknown() {
				body, _ = sjson.Set(body, "match.destination-address.ipv4.address-prefix"+"."+strconv.Itoa(index)+"."+"netmask", item.Netmask.ValueString())
			}
		}
	}
	if len(data.MatchDestinationAddressIpv6) > 0 {
		body, _ = sjson.Set(body, "match.destination-address.ipv6.address-prefix", []interface{}{})
		for index, item := range data.MatchDestinationAddressIpv6 {
			if !item.Address.IsNull() && !item.Address.IsUnknown() {
				body, _ = sjson.Set(body, "match.destination-address.ipv6.address-prefix"+"."+strconv.Itoa(index)+"."+"address", item.Address.ValueString())
			}
			if !item.PrefixLength.IsNull() && !item.PrefixLength.IsUnknown() {
				body, _ = sjson.Set(body, "match.destination-address.ipv6.address-prefix"+"."+strconv.Itoa(index)+"."+"prefix-length", strconv.FormatInt(item.PrefixLength.ValueInt64(), 10))
			}
		}
	}
	if len(data.MatchSourceAddressIpv4) > 0 {
		body, _ = sjson.Set(body, "match.source-address.ipv4.address-prefix", []interface{}{})
		for index, item := range data.MatchSourceAddressIpv4 {
			if !item.Address.IsNull() && !item.Address.IsUnknown() {
				body, _ = sjson.Set(body, "match.source-address.ipv4.address-prefix"+"."+strconv.Itoa(index)+"."+"address", item.Address.ValueString())
			}
			if !item.Netmask.IsNull() && !item.Netmask.IsUnknown() {
				body, _ = sjson.Set(body, "match.source-address.ipv4.address-prefix"+"."+strconv.Itoa(index)+"."+"netmask", item.Netmask.ValueString())
			}
		}
	}
	if len(data.MatchSourceAddressIpv6) > 0 {
		body, _ = sjson.Set(body, "match.source-address.ipv6.address-prefix", []interface{}{})
		for index, item := range data.MatchSourceAddressIpv6 {
			if !item.Address.IsNull() && !item.Address.IsUnknown() {
				body, _ = sjson.Set(body, "match.source-address.ipv6.address-prefix"+"."+strconv.Itoa(index)+"."+"address", item.Address.ValueString())
			}
			if !item.PrefixLength.IsNull() && !item.PrefixLength.IsUnknown() {
				body, _ = sjson.Set(body, "match.source-address.ipv6.address-prefix"+"."+strconv.Itoa(index)+"."+"prefix-length", strconv.FormatInt(item.PrefixLength.ValueInt64(), 10))
			}
		}
	}
	return body
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin getVersionConstraints

// GetVersionConstraints returns the version constraints for all fields
func (data ClassMapTraffic) GetVersionConstraints() []helpers.FieldVersionConstraint {
	constraints := make([]helpers.FieldVersionConstraint, 0)

	if len(constraints) == 0 {
		return nil
	}
	return constraints
}

// End of section. //template:end getVersionConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getRangeConstraints

// GetRangeConstraints returns the version-specific range constraints for integer fields
func (data ClassMapTraffic) GetRangeConstraints() []helpers.FieldRangeConstraint {
	return nil
}

// End of section. //template:end getRangeConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getEnumConstraints

// GetEnumConstraints returns the version-specific enum constraints for string fields
func (data ClassMapTraffic) GetEnumConstraints() []helpers.FieldEnumConstraint {
	return nil
}

// End of section. //template:end getEnumConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getStringLengthConstraints

// GetStringLengthConstraints returns the version-specific string length constraints
func (data ClassMapTraffic) GetStringLengthConstraints() []helpers.FieldStringLengthConstraint {
	return nil
}

// End of section. //template:end getStringLengthConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getPatternConstraints

// GetPatternConstraints returns the version-specific string pattern constraints
func (data ClassMapTraffic) GetPatternConstraints() []helpers.FieldPatternConstraint {
	return nil
}

// End of section. //template:end getPatternConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getDefaultConstraints
// End of section. //template:end getDefaultConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody
func (data *ClassMapTraffic) updateFromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "match-all"); !data.MatchAll.IsNull() {
		if value.Exists() {
			data.MatchAll = types.BoolValue(true)
		} else {
			data.MatchAll = types.BoolValue(false)
		}
	} else {
		data.MatchAll = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "match-any"); !data.MatchAny.IsNull() {
		if value.Exists() {
			data.MatchAny = types.BoolValue(true)
		} else {
			data.MatchAny = types.BoolValue(false)
		}
	} else {
		data.MatchAny = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "description"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := gjson.GetBytes(res, "match.access-group.ipv4"); value.Exists() && !data.MatchAccessGroupIpv4.IsNull() {
		data.MatchAccessGroupIpv4 = helpers.GetStringList(value.Array())
	} else {
		data.MatchAccessGroupIpv4 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.access-group.ipv6"); value.Exists() && !data.MatchAccessGroupIpv6.IsNull() {
		data.MatchAccessGroupIpv6 = helpers.GetStringList(value.Array())
	} else {
		data.MatchAccessGroupIpv6 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.cos.value"); value.Exists() && !data.MatchCos.IsNull() {
		data.MatchCos = helpers.GetInt64List(value.Array())
	} else {
		data.MatchCos = types.ListNull(types.Int64Type)
	}
	if value := gjson.GetBytes(res, "match.cos-inner.value"); value.Exists() && !data.MatchCosInner.IsNull() {
		data.MatchCosInner = helpers.GetInt64List(value.Array())
	} else {
		data.MatchCosInner = types.ListNull(types.Int64Type)
	}
	for i := range data.MatchDestinationAddressIpv4 {
		keys := [...]string{"address", "netmask"}
		keyValues := [...]string{data.MatchDestinationAddressIpv4[i].Address.ValueString(), data.MatchDestinationAddressIpv4[i].Netmask.ValueString()}

		var r gjson.Result
		gjson.GetBytes(res, "match.destination-address.ipv4.address-prefix").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("address"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.MatchDestinationAddressIpv4[i].Address.IsNull() {
			data.MatchDestinationAddressIpv4[i].Address = types.StringValue(value.String())
		} else {
			data.MatchDestinationAddressIpv4[i].Address = types.StringNull()
		}
		if value := r.Get("netmask"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.MatchDestinationAddressIpv4[i].Netmask.IsNull() {
			data.MatchDestinationAddressIpv4[i].Netmask = types.StringValue(value.String())
		} else {
			data.MatchDestinationAddressIpv4[i].Netmask = types.StringNull()
		}
	}
	for i := range data.MatchDestinationAddressIpv6 {
		keys := [...]string{"address", "prefix-length"}
		keyValues := [...]string{data.MatchDestinationAddressIpv6[i].Address.ValueString(), strconv.FormatInt(data.MatchDestinationAddressIpv6[i].PrefixLength.ValueInt64(), 10)}

		var r gjson.Result
		gjson.GetBytes(res, "match.destination-address.ipv6.address-prefix").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("address"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.MatchDestinationAddressIpv6[i].Address.IsNull() {
			data.MatchDestinationAddressIpv6[i].Address = types.StringValue(value.String())
		} else {
			data.MatchDestinationAddressIpv6[i].Address = types.StringNull()
		}
		if value := r.Get("prefix-length"); value.Exists() && !data.MatchDestinationAddressIpv6[i].PrefixLength.IsNull() {
			data.MatchDestinationAddressIpv6[i].PrefixLength = types.Int64Value(value.Int())
		} else {
			data.MatchDestinationAddressIpv6[i].PrefixLength = types.Int64Null()
		}
	}
	if value := gjson.GetBytes(res, "match.destination-address.mac"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.MatchDestinationMac.IsNull() {
		data.MatchDestinationMac = types.StringValue(value.String())
	} else {
		data.MatchDestinationMac = types.StringNull()
	}
	if value := gjson.GetBytes(res, "match.destination-port.port-number"); value.Exists() && !data.MatchDestinationPort.IsNull() {
		data.MatchDestinationPort = helpers.GetStringList(value.Array())
	} else {
		data.MatchDestinationPort = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.dscp.value"); value.Exists() && !data.MatchDscp.IsNull() {
		data.MatchDscp = helpers.GetStringList(value.Array())
	} else {
		data.MatchDscp = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.dscp-ipv4.value"); value.Exists() && !data.MatchDscpIpv4.IsNull() {
		data.MatchDscpIpv4 = helpers.GetStringList(value.Array())
	} else {
		data.MatchDscpIpv4 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.dscp-ipv6.value"); value.Exists() && !data.MatchDscpIpv6.IsNull() {
		data.MatchDscpIpv6 = helpers.GetStringList(value.Array())
	} else {
		data.MatchDscpIpv6 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ethertype.value"); value.Exists() && !data.MatchEthertype.IsNull() {
		data.MatchEthertype = helpers.GetStringList(value.Array())
	} else {
		data.MatchEthertype = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.flow-tag.tag-number"); value.Exists() && !data.MatchFlowTag.IsNull() {
		data.MatchFlowTag = helpers.GetStringList(value.Array())
	} else {
		data.MatchFlowTag = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.fragment-type.dont-fragment"); !data.MatchFragmentTypeDontFragment.IsNull() {
		if value.Exists() {
			data.MatchFragmentTypeDontFragment = types.BoolValue(true)
		} else {
			data.MatchFragmentTypeDontFragment = types.BoolValue(false)
		}
	} else {
		data.MatchFragmentTypeDontFragment = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "match.fragment-type.first-fragment"); !data.MatchFragmentTypeFirstFragment.IsNull() {
		if value.Exists() {
			data.MatchFragmentTypeFirstFragment = types.BoolValue(true)
		} else {
			data.MatchFragmentTypeFirstFragment = types.BoolValue(false)
		}
	} else {
		data.MatchFragmentTypeFirstFragment = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "match.fragment-type.is-fragment"); !data.MatchFragmentTypeIsFragment.IsNull() {
		if value.Exists() {
			data.MatchFragmentTypeIsFragment = types.BoolValue(true)
		} else {
			data.MatchFragmentTypeIsFragment = types.BoolValue(false)
		}
	} else {
		data.MatchFragmentTypeIsFragment = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "match.fragment-type.last-fragment"); !data.MatchFragmentTypeLastFragment.IsNull() {
		if value.Exists() {
			data.MatchFragmentTypeLastFragment = types.BoolValue(true)
		} else {
			data.MatchFragmentTypeLastFragment = types.BoolValue(false)
		}
	} else {
		data.MatchFragmentTypeLastFragment = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "match.ipv4.icmp-code.value"); value.Exists() && !data.MatchIpv4IcmpCode.IsNull() {
		data.MatchIpv4IcmpCode = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv4IcmpCode = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ipv4.icmp-type.value"); value.Exists() && !data.MatchIpv4IcmpType.IsNull() {
		data.MatchIpv4IcmpType = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv4IcmpType = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ipv6.icmp-code.value"); value.Exists() && !data.MatchIpv6IcmpCode.IsNull() {
		data.MatchIpv6IcmpCode = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv6IcmpCode = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ipv6.icmp-type.value"); value.Exists() && !data.MatchIpv6IcmpType.IsNull() {
		data.MatchIpv6IcmpType = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv6IcmpType = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.mpls.experimental.topmost.label"); value.Exists() && !data.MatchMplsExperimentalTopmost.IsNull() {
		data.MatchMplsExperimentalTopmost = helpers.GetInt64List(value.Array())
	} else {
		data.MatchMplsExperimentalTopmost = types.ListNull(types.Int64Type)
	}
	if value := gjson.GetBytes(res, "match.packet.length.value"); value.Exists() && !data.MatchPacketLength.IsNull() {
		data.MatchPacketLength = helpers.GetStringList(value.Array())
	} else {
		data.MatchPacketLength = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.precedence.value"); value.Exists() && !data.MatchPrecedence.IsNull() {
		data.MatchPrecedence = helpers.GetStringList(value.Array())
	} else {
		data.MatchPrecedence = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.precedence-ipv4.value"); value.Exists() && !data.MatchPrecedenceIpv4.IsNull() {
		data.MatchPrecedenceIpv4 = helpers.GetStringList(value.Array())
	} else {
		data.MatchPrecedenceIpv4 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.precedence-ipv6.value"); value.Exists() && !data.MatchPrecedenceIpv6.IsNull() {
		data.MatchPrecedenceIpv6 = helpers.GetStringList(value.Array())
	} else {
		data.MatchPrecedenceIpv6 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.protocol.number"); value.Exists() && !data.MatchProtocol.IsNull() {
		data.MatchProtocol = helpers.GetStringList(value.Array())
	} else {
		data.MatchProtocol = types.ListNull(types.StringType)
	}
	for i := range data.MatchSourceAddressIpv4 {
		keys := [...]string{"address", "netmask"}
		keyValues := [...]string{data.MatchSourceAddressIpv4[i].Address.ValueString(), data.MatchSourceAddressIpv4[i].Netmask.ValueString()}

		var r gjson.Result
		gjson.GetBytes(res, "match.source-address.ipv4.address-prefix").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("address"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.MatchSourceAddressIpv4[i].Address.IsNull() {
			data.MatchSourceAddressIpv4[i].Address = types.StringValue(value.String())
		} else {
			data.MatchSourceAddressIpv4[i].Address = types.StringNull()
		}
		if value := r.Get("netmask"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.MatchSourceAddressIpv4[i].Netmask.IsNull() {
			data.MatchSourceAddressIpv4[i].Netmask = types.StringValue(value.String())
		} else {
			data.MatchSourceAddressIpv4[i].Netmask = types.StringNull()
		}
	}
	for i := range data.MatchSourceAddressIpv6 {
		keys := [...]string{"address", "prefix-length"}
		keyValues := [...]string{data.MatchSourceAddressIpv6[i].Address.ValueString(), strconv.FormatInt(data.MatchSourceAddressIpv6[i].PrefixLength.ValueInt64(), 10)}

		var r gjson.Result
		gjson.GetBytes(res, "match.source-address.ipv6.address-prefix").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("address"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.MatchSourceAddressIpv6[i].Address.IsNull() {
			data.MatchSourceAddressIpv6[i].Address = types.StringValue(value.String())
		} else {
			data.MatchSourceAddressIpv6[i].Address = types.StringNull()
		}
		if value := r.Get("prefix-length"); value.Exists() && !data.MatchSourceAddressIpv6[i].PrefixLength.IsNull() {
			data.MatchSourceAddressIpv6[i].PrefixLength = types.Int64Value(value.Int())
		} else {
			data.MatchSourceAddressIpv6[i].PrefixLength = types.Int64Null()
		}
	}
	if value := gjson.GetBytes(res, "match.source-address.mac"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.MatchSourceMac.IsNull() {
		data.MatchSourceMac = types.StringValue(value.String())
	} else {
		data.MatchSourceMac = types.StringNull()
	}
	if value := gjson.GetBytes(res, "match.source-port.number"); value.Exists() && !data.MatchSourcePort.IsNull() {
		data.MatchSourcePort = helpers.GetStringList(value.Array())
	} else {
		data.MatchSourcePort = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.tcp-flag.value"); value.Exists() && !data.MatchTcpFlag.IsNull() {
		data.MatchTcpFlag = types.Int64Value(value.Int())
	} else {
		data.MatchTcpFlag = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "match.tcp-flag.any"); !data.MatchTcpFlagAny.IsNull() {
		if value.Exists() {
			data.MatchTcpFlagAny = types.BoolValue(true)
		} else {
			data.MatchTcpFlagAny = types.BoolValue(false)
		}
	} else {
		data.MatchTcpFlagAny = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "match.vlan.vlan-id"); value.Exists() && !data.MatchVlan.IsNull() {
		data.MatchVlan = helpers.GetStringList(value.Array())
	} else {
		data.MatchVlan = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.vlan-inner.vlan-id"); value.Exists() && !data.MatchVlanInner.IsNull() {
		data.MatchVlanInner = helpers.GetStringList(value.Array())
	} else {
		data.MatchVlanInner = types.ListNull(types.StringType)
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *ClassMapTraffic) fromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "match-all"); value.Exists() {
		data.MatchAll = types.BoolValue(true)
	} else {
		data.MatchAll = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match-any"); value.Exists() {
		data.MatchAny = types.BoolValue(true)
	} else {
		data.MatchAny = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "description"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.Description = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "match.access-group.ipv4"); value.Exists() {
		data.MatchAccessGroupIpv4 = helpers.GetStringList(value.Array())
	} else {
		data.MatchAccessGroupIpv4 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.access-group.ipv6"); value.Exists() {
		data.MatchAccessGroupIpv6 = helpers.GetStringList(value.Array())
	} else {
		data.MatchAccessGroupIpv6 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.cos.value"); value.Exists() {
		data.MatchCos = helpers.GetInt64List(value.Array())
	} else {
		data.MatchCos = types.ListNull(types.Int64Type)
	}
	if value := gjson.GetBytes(res, "match.cos-inner.value"); value.Exists() {
		data.MatchCosInner = helpers.GetInt64List(value.Array())
	} else {
		data.MatchCosInner = types.ListNull(types.Int64Type)
	}
	if value := gjson.GetBytes(res, "match.destination-address.ipv4.address-prefix"); value.Exists() {
		data.MatchDestinationAddressIpv4 = make([]ClassMapTrafficMatchDestinationAddressIpv4, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := ClassMapTrafficMatchDestinationAddressIpv4{}
			if cValue := v.Get("address"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := v.Get("netmask"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Netmask = types.StringValue(cValue.String())
			}
			data.MatchDestinationAddressIpv4 = append(data.MatchDestinationAddressIpv4, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "match.destination-address.ipv6.address-prefix"); value.Exists() {
		data.MatchDestinationAddressIpv6 = make([]ClassMapTrafficMatchDestinationAddressIpv6, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := ClassMapTrafficMatchDestinationAddressIpv6{}
			if cValue := v.Get("address"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := v.Get("prefix-length"); cValue.Exists() {
				item.PrefixLength = types.Int64Value(cValue.Int())
			}
			data.MatchDestinationAddressIpv6 = append(data.MatchDestinationAddressIpv6, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "match.destination-address.mac"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.MatchDestinationMac = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "match.destination-port.port-number"); value.Exists() {
		data.MatchDestinationPort = helpers.GetStringList(value.Array())
	} else {
		data.MatchDestinationPort = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.dscp.value"); value.Exists() {
		data.MatchDscp = helpers.GetStringList(value.Array())
	} else {
		data.MatchDscp = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.dscp-ipv4.value"); value.Exists() {
		data.MatchDscpIpv4 = helpers.GetStringList(value.Array())
	} else {
		data.MatchDscpIpv4 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.dscp-ipv6.value"); value.Exists() {
		data.MatchDscpIpv6 = helpers.GetStringList(value.Array())
	} else {
		data.MatchDscpIpv6 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ethertype.value"); value.Exists() {
		data.MatchEthertype = helpers.GetStringList(value.Array())
	} else {
		data.MatchEthertype = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.flow-tag.tag-number"); value.Exists() {
		data.MatchFlowTag = helpers.GetStringList(value.Array())
	} else {
		data.MatchFlowTag = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.fragment-type.dont-fragment"); value.Exists() {
		data.MatchFragmentTypeDontFragment = types.BoolValue(true)
	} else {
		data.MatchFragmentTypeDontFragment = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match.fragment-type.first-fragment"); value.Exists() {
		data.MatchFragmentTypeFirstFragment = types.BoolValue(true)
	} else {
		data.MatchFragmentTypeFirstFragment = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match.fragment-type.is-fragment"); value.Exists() {
		data.MatchFragmentTypeIsFragment = types.BoolValue(true)
	} else {
		data.MatchFragmentTypeIsFragment = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match.fragment-type.last-fragment"); value.Exists() {
		data.MatchFragmentTypeLastFragment = types.BoolValue(true)
	} else {
		data.MatchFragmentTypeLastFragment = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match.ipv4.icmp-code.value"); value.Exists() {
		data.MatchIpv4IcmpCode = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv4IcmpCode = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ipv4.icmp-type.value"); value.Exists() {
		data.MatchIpv4IcmpType = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv4IcmpType = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ipv6.icmp-code.value"); value.Exists() {
		data.MatchIpv6IcmpCode = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv6IcmpCode = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ipv6.icmp-type.value"); value.Exists() {
		data.MatchIpv6IcmpType = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv6IcmpType = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.mpls.experimental.topmost.label"); value.Exists() {
		data.MatchMplsExperimentalTopmost = helpers.GetInt64List(value.Array())
	} else {
		data.MatchMplsExperimentalTopmost = types.ListNull(types.Int64Type)
	}
	if value := gjson.GetBytes(res, "match.packet.length.value"); value.Exists() {
		data.MatchPacketLength = helpers.GetStringList(value.Array())
	} else {
		data.MatchPacketLength = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.precedence.value"); value.Exists() {
		data.MatchPrecedence = helpers.GetStringList(value.Array())
	} else {
		data.MatchPrecedence = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.precedence-ipv4.value"); value.Exists() {
		data.MatchPrecedenceIpv4 = helpers.GetStringList(value.Array())
	} else {
		data.MatchPrecedenceIpv4 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.precedence-ipv6.value"); value.Exists() {
		data.MatchPrecedenceIpv6 = helpers.GetStringList(value.Array())
	} else {
		data.MatchPrecedenceIpv6 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.protocol.number"); value.Exists() {
		data.MatchProtocol = helpers.GetStringList(value.Array())
	} else {
		data.MatchProtocol = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.source-address.ipv4.address-prefix"); value.Exists() {
		data.MatchSourceAddressIpv4 = make([]ClassMapTrafficMatchSourceAddressIpv4, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := ClassMapTrafficMatchSourceAddressIpv4{}
			if cValue := v.Get("address"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := v.Get("netmask"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Netmask = types.StringValue(cValue.String())
			}
			data.MatchSourceAddressIpv4 = append(data.MatchSourceAddressIpv4, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "match.source-address.ipv6.address-prefix"); value.Exists() {
		data.MatchSourceAddressIpv6 = make([]ClassMapTrafficMatchSourceAddressIpv6, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := ClassMapTrafficMatchSourceAddressIpv6{}
			if cValue := v.Get("address"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := v.Get("prefix-length"); cValue.Exists() {
				item.PrefixLength = types.Int64Value(cValue.Int())
			}
			data.MatchSourceAddressIpv6 = append(data.MatchSourceAddressIpv6, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "match.source-address.mac"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.MatchSourceMac = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "match.source-port.number"); value.Exists() {
		data.MatchSourcePort = helpers.GetStringList(value.Array())
	} else {
		data.MatchSourcePort = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.tcp-flag.value"); value.Exists() {
		data.MatchTcpFlag = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "match.tcp-flag.any"); value.Exists() {
		data.MatchTcpFlagAny = types.BoolValue(true)
	} else {
		data.MatchTcpFlagAny = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match.vlan.vlan-id"); value.Exists() {
		data.MatchVlan = helpers.GetStringList(value.Array())
	} else {
		data.MatchVlan = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.vlan-inner.vlan-id"); value.Exists() {
		data.MatchVlanInner = helpers.GetStringList(value.Array())
	} else {
		data.MatchVlanInner = types.ListNull(types.StringType)
	}
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyData

func (data *ClassMapTrafficData) fromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "match-all"); value.Exists() {
		data.MatchAll = types.BoolValue(true)
	} else {
		data.MatchAll = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match-any"); value.Exists() {
		data.MatchAny = types.BoolValue(true)
	} else {
		data.MatchAny = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "description"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.Description = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "match.access-group.ipv4"); value.Exists() {
		data.MatchAccessGroupIpv4 = helpers.GetStringList(value.Array())
	} else {
		data.MatchAccessGroupIpv4 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.access-group.ipv6"); value.Exists() {
		data.MatchAccessGroupIpv6 = helpers.GetStringList(value.Array())
	} else {
		data.MatchAccessGroupIpv6 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.cos.value"); value.Exists() {
		data.MatchCos = helpers.GetInt64List(value.Array())
	} else {
		data.MatchCos = types.ListNull(types.Int64Type)
	}
	if value := gjson.GetBytes(res, "match.cos-inner.value"); value.Exists() {
		data.MatchCosInner = helpers.GetInt64List(value.Array())
	} else {
		data.MatchCosInner = types.ListNull(types.Int64Type)
	}
	if value := gjson.GetBytes(res, "match.destination-address.ipv4.address-prefix"); value.Exists() {
		data.MatchDestinationAddressIpv4 = make([]ClassMapTrafficMatchDestinationAddressIpv4, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := ClassMapTrafficMatchDestinationAddressIpv4{}
			if cValue := v.Get("address"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := v.Get("netmask"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Netmask = types.StringValue(cValue.String())
			}
			data.MatchDestinationAddressIpv4 = append(data.MatchDestinationAddressIpv4, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "match.destination-address.ipv6.address-prefix"); value.Exists() {
		data.MatchDestinationAddressIpv6 = make([]ClassMapTrafficMatchDestinationAddressIpv6, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := ClassMapTrafficMatchDestinationAddressIpv6{}
			if cValue := v.Get("address"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := v.Get("prefix-length"); cValue.Exists() {
				item.PrefixLength = types.Int64Value(cValue.Int())
			}
			data.MatchDestinationAddressIpv6 = append(data.MatchDestinationAddressIpv6, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "match.destination-address.mac"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.MatchDestinationMac = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "match.destination-port.port-number"); value.Exists() {
		data.MatchDestinationPort = helpers.GetStringList(value.Array())
	} else {
		data.MatchDestinationPort = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.dscp.value"); value.Exists() {
		data.MatchDscp = helpers.GetStringList(value.Array())
	} else {
		data.MatchDscp = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.dscp-ipv4.value"); value.Exists() {
		data.MatchDscpIpv4 = helpers.GetStringList(value.Array())
	} else {
		data.MatchDscpIpv4 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.dscp-ipv6.value"); value.Exists() {
		data.MatchDscpIpv6 = helpers.GetStringList(value.Array())
	} else {
		data.MatchDscpIpv6 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ethertype.value"); value.Exists() {
		data.MatchEthertype = helpers.GetStringList(value.Array())
	} else {
		data.MatchEthertype = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.flow-tag.tag-number"); value.Exists() {
		data.MatchFlowTag = helpers.GetStringList(value.Array())
	} else {
		data.MatchFlowTag = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.fragment-type.dont-fragment"); value.Exists() {
		data.MatchFragmentTypeDontFragment = types.BoolValue(true)
	} else {
		data.MatchFragmentTypeDontFragment = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match.fragment-type.first-fragment"); value.Exists() {
		data.MatchFragmentTypeFirstFragment = types.BoolValue(true)
	} else {
		data.MatchFragmentTypeFirstFragment = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match.fragment-type.is-fragment"); value.Exists() {
		data.MatchFragmentTypeIsFragment = types.BoolValue(true)
	} else {
		data.MatchFragmentTypeIsFragment = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match.fragment-type.last-fragment"); value.Exists() {
		data.MatchFragmentTypeLastFragment = types.BoolValue(true)
	} else {
		data.MatchFragmentTypeLastFragment = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match.ipv4.icmp-code.value"); value.Exists() {
		data.MatchIpv4IcmpCode = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv4IcmpCode = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ipv4.icmp-type.value"); value.Exists() {
		data.MatchIpv4IcmpType = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv4IcmpType = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ipv6.icmp-code.value"); value.Exists() {
		data.MatchIpv6IcmpCode = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv6IcmpCode = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.ipv6.icmp-type.value"); value.Exists() {
		data.MatchIpv6IcmpType = helpers.GetStringList(value.Array())
	} else {
		data.MatchIpv6IcmpType = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.mpls.experimental.topmost.label"); value.Exists() {
		data.MatchMplsExperimentalTopmost = helpers.GetInt64List(value.Array())
	} else {
		data.MatchMplsExperimentalTopmost = types.ListNull(types.Int64Type)
	}
	if value := gjson.GetBytes(res, "match.packet.length.value"); value.Exists() {
		data.MatchPacketLength = helpers.GetStringList(value.Array())
	} else {
		data.MatchPacketLength = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.precedence.value"); value.Exists() {
		data.MatchPrecedence = helpers.GetStringList(value.Array())
	} else {
		data.MatchPrecedence = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.precedence-ipv4.value"); value.Exists() {
		data.MatchPrecedenceIpv4 = helpers.GetStringList(value.Array())
	} else {
		data.MatchPrecedenceIpv4 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.precedence-ipv6.value"); value.Exists() {
		data.MatchPrecedenceIpv6 = helpers.GetStringList(value.Array())
	} else {
		data.MatchPrecedenceIpv6 = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.protocol.number"); value.Exists() {
		data.MatchProtocol = helpers.GetStringList(value.Array())
	} else {
		data.MatchProtocol = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.source-address.ipv4.address-prefix"); value.Exists() {
		data.MatchSourceAddressIpv4 = make([]ClassMapTrafficMatchSourceAddressIpv4, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := ClassMapTrafficMatchSourceAddressIpv4{}
			if cValue := v.Get("address"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := v.Get("netmask"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Netmask = types.StringValue(cValue.String())
			}
			data.MatchSourceAddressIpv4 = append(data.MatchSourceAddressIpv4, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "match.source-address.ipv6.address-prefix"); value.Exists() {
		data.MatchSourceAddressIpv6 = make([]ClassMapTrafficMatchSourceAddressIpv6, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := ClassMapTrafficMatchSourceAddressIpv6{}
			if cValue := v.Get("address"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := v.Get("prefix-length"); cValue.Exists() {
				item.PrefixLength = types.Int64Value(cValue.Int())
			}
			data.MatchSourceAddressIpv6 = append(data.MatchSourceAddressIpv6, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "match.source-address.mac"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.MatchSourceMac = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "match.source-port.number"); value.Exists() {
		data.MatchSourcePort = helpers.GetStringList(value.Array())
	} else {
		data.MatchSourcePort = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.tcp-flag.value"); value.Exists() {
		data.MatchTcpFlag = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "match.tcp-flag.any"); value.Exists() {
		data.MatchTcpFlagAny = types.BoolValue(true)
	} else {
		data.MatchTcpFlagAny = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "match.vlan.vlan-id"); value.Exists() {
		data.MatchVlan = helpers.GetStringList(value.Array())
	} else {
		data.MatchVlan = types.ListNull(types.StringType)
	}
	if value := gjson.GetBytes(res, "match.vlan-inner.vlan-id"); value.Exists() {
		data.MatchVlanInner = helpers.GetStringList(value.Array())
	} else {
		data.MatchVlanInner = types.ListNull(types.StringType)
	}
}

// End of section. //template:end fromBodyData

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletedItems

func (data *ClassMapTraffic) getDeletedItems(ctx context.Context, state ClassMapTraffic, version string) []string {
	deletedItems := make([]string, 0)
	if !state.MatchVlanInner.IsNull() && data.MatchVlanInner.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/vlan-inner/vlan-id"))
	}
	if !state.MatchVlan.IsNull() && data.MatchVlan.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/vlan/vlan-id"))
	}
	if !state.MatchTcpFlagAny.IsNull() && data.MatchTcpFlagAny.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/tcp-flag/any"))
	}
	if !state.MatchTcpFlag.IsNull() && data.MatchTcpFlag.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/tcp-flag/value"))
	}
	if !state.MatchSourcePort.IsNull() && data.MatchSourcePort.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/source-port/number"))
	}
	if !state.MatchSourceMac.IsNull() && data.MatchSourceMac.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/source-address/mac"))
	}
	for i := range state.MatchSourceAddressIpv6 {
		keys := [...]string{"address", "prefix-length"}
		stateKeyValues := [...]string{state.MatchSourceAddressIpv6[i].Address.ValueString(), strconv.FormatInt(state.MatchSourceAddressIpv6[i].PrefixLength.ValueInt64(), 10)}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + stateKeyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(state.MatchSourceAddressIpv6[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(state.MatchSourceAddressIpv6[i].PrefixLength.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.MatchSourceAddressIpv6 {
			found = true
			if state.MatchSourceAddressIpv6[i].Address.ValueString() != data.MatchSourceAddressIpv6[j].Address.ValueString() {
				found = false
			}
			if state.MatchSourceAddressIpv6[i].PrefixLength.ValueInt64() != data.MatchSourceAddressIpv6[j].PrefixLength.ValueInt64() {
				found = false
			}
			if found {
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, fmt.Sprintf("%v/%v%v", state.getPath(), "match/source-address/ipv6/address-prefix", keyString))
		}
	}
	for i := range state.MatchSourceAddressIpv4 {
		keys := [...]string{"address", "netmask"}
		stateKeyValues := [...]string{state.MatchSourceAddressIpv4[i].Address.ValueString(), state.MatchSourceAddressIpv4[i].Netmask.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + stateKeyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(state.MatchSourceAddressIpv4[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(state.MatchSourceAddressIpv4[i].Netmask.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.MatchSourceAddressIpv4 {
			found = true
			if state.MatchSourceAddressIpv4[i].Address.ValueString() != data.MatchSourceAddressIpv4[j].Address.ValueString() {
				found = false
			}
			if state.MatchSourceAddressIpv4[i].Netmask.ValueString() != data.MatchSourceAddressIpv4[j].Netmask.ValueString() {
				found = false
			}
			if found {
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, fmt.Sprintf("%v/%v%v", state.getPath(), "match/source-address/ipv4/address-prefix", keyString))
		}
	}
	if !state.MatchProtocol.IsNull() && data.MatchProtocol.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/protocol/number"))
	}
	if !state.MatchPrecedenceIpv6.IsNull() && data.MatchPrecedenceIpv6.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/precedence-ipv6/value"))
	}
	if !state.MatchPrecedenceIpv4.IsNull() && data.MatchPrecedenceIpv4.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/precedence-ipv4/value"))
	}
	if !state.MatchPrecedence.IsNull() && data.MatchPrecedence.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/precedence/value"))
	}
	if !state.MatchPacketLength.IsNull() && data.MatchPacketLength.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/packet/length/value"))
	}
	if !state.MatchMplsExperimentalTopmost.IsNull() && data.MatchMplsExperimentalTopmost.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/mpls/experimental/topmost/label"))
	}
	if !state.MatchIpv6IcmpType.IsNull() && data.MatchIpv6IcmpType.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/ipv6/icmp-type/value"))
	}
	if !state.MatchIpv6IcmpCode.IsNull() && data.MatchIpv6IcmpCode.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/ipv6/icmp-code/value"))
	}
	if !state.MatchIpv4IcmpType.IsNull() && data.MatchIpv4IcmpType.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/ipv4/icmp-type/value"))
	}
	if !state.MatchIpv4IcmpCode.IsNull() && data.MatchIpv4IcmpCode.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/ipv4/icmp-code/value"))
	}
	if !state.MatchFragmentTypeLastFragment.IsNull() && data.MatchFragmentTypeLastFragment.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/fragment-type/last-fragment"))
	}
	if !state.MatchFragmentTypeIsFragment.IsNull() && data.MatchFragmentTypeIsFragment.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/fragment-type/is-fragment"))
	}
	if !state.MatchFragmentTypeFirstFragment.IsNull() && data.MatchFragmentTypeFirstFragment.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/fragment-type/first-fragment"))
	}
	if !state.MatchFragmentTypeDontFragment.IsNull() && data.MatchFragmentTypeDontFragment.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/fragment-type/dont-fragment"))
	}
	if !state.MatchFlowTag.IsNull() && data.MatchFlowTag.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/flow-tag/tag-number"))
	}
	if !state.MatchEthertype.IsNull() && data.MatchEthertype.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/ethertype/value"))
	}
	if !state.MatchDscpIpv6.IsNull() && data.MatchDscpIpv6.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/dscp-ipv6/value"))
	}
	if !state.MatchDscpIpv4.IsNull() && data.MatchDscpIpv4.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/dscp-ipv4/value"))
	}
	if !state.MatchDscp.IsNull() && data.MatchDscp.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/dscp/value"))
	}
	if !state.MatchDestinationPort.IsNull() && data.MatchDestinationPort.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/destination-port/port-number"))
	}
	if !state.MatchDestinationMac.IsNull() && data.MatchDestinationMac.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/destination-address/mac"))
	}
	for i := range state.MatchDestinationAddressIpv6 {
		keys := [...]string{"address", "prefix-length"}
		stateKeyValues := [...]string{state.MatchDestinationAddressIpv6[i].Address.ValueString(), strconv.FormatInt(state.MatchDestinationAddressIpv6[i].PrefixLength.ValueInt64(), 10)}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + stateKeyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(state.MatchDestinationAddressIpv6[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(state.MatchDestinationAddressIpv6[i].PrefixLength.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.MatchDestinationAddressIpv6 {
			found = true
			if state.MatchDestinationAddressIpv6[i].Address.ValueString() != data.MatchDestinationAddressIpv6[j].Address.ValueString() {
				found = false
			}
			if state.MatchDestinationAddressIpv6[i].PrefixLength.ValueInt64() != data.MatchDestinationAddressIpv6[j].PrefixLength.ValueInt64() {
				found = false
			}
			if found {
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, fmt.Sprintf("%v/%v%v", state.getPath(), "match/destination-address/ipv6/address-prefix", keyString))
		}
	}
	for i := range state.MatchDestinationAddressIpv4 {
		keys := [...]string{"address", "netmask"}
		stateKeyValues := [...]string{state.MatchDestinationAddressIpv4[i].Address.ValueString(), state.MatchDestinationAddressIpv4[i].Netmask.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + stateKeyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(state.MatchDestinationAddressIpv4[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(state.MatchDestinationAddressIpv4[i].Netmask.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.MatchDestinationAddressIpv4 {
			found = true
			if state.MatchDestinationAddressIpv4[i].Address.ValueString() != data.MatchDestinationAddressIpv4[j].Address.ValueString() {
				found = false
			}
			if state.MatchDestinationAddressIpv4[i].Netmask.ValueString() != data.MatchDestinationAddressIpv4[j].Netmask.ValueString() {
				found = false
			}
			if found {
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, fmt.Sprintf("%v/%v%v", state.getPath(), "match/destination-address/ipv4/address-prefix", keyString))
		}
	}
	if !state.MatchCosInner.IsNull() && data.MatchCosInner.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/cos-inner/value"))
	}
	if !state.MatchCos.IsNull() && data.MatchCos.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/cos/value"))
	}
	if !state.MatchAccessGroupIpv6.IsNull() && data.MatchAccessGroupIpv6.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/access-group/ipv6"))
	}
	if !state.MatchAccessGroupIpv4.IsNull() && data.MatchAccessGroupIpv4.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match/access-group/ipv4"))
	}
	if !state.Description.IsNull() && data.Description.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "description"))
	}
	if !state.MatchAny.IsNull() && data.MatchAny.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match-any"))
	}
	if !state.MatchAll.IsNull() && data.MatchAll.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "match-all"))
	}
	return deletedItems
}

// End of section. //template:end getDeletedItems

// Section below is generated&owned by "gen/generator.go". //template:begin getEmptyLeafsDelete

func (data *ClassMapTraffic) getEmptyLeafsDelete(ctx context.Context, version string) []string {
	emptyLeafsDelete := make([]string, 0)
	if !data.MatchTcpFlagAny.IsNull() && !data.MatchTcpFlagAny.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "match/tcp-flag/any"))
	}
	for i := range data.MatchSourceAddressIpv6 {
		keys := [...]string{"address", "prefix-length"}
		keyValues := [...]string{data.MatchSourceAddressIpv6[i].Address.ValueString(), strconv.FormatInt(data.MatchSourceAddressIpv6[i].PrefixLength.ValueInt64(), 10)}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
	}
	for i := range data.MatchSourceAddressIpv4 {
		keys := [...]string{"address", "netmask"}
		keyValues := [...]string{data.MatchSourceAddressIpv4[i].Address.ValueString(), data.MatchSourceAddressIpv4[i].Netmask.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
	}
	if !data.MatchFragmentTypeLastFragment.IsNull() && !data.MatchFragmentTypeLastFragment.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "match/fragment-type/last-fragment"))
	}
	if !data.MatchFragmentTypeIsFragment.IsNull() && !data.MatchFragmentTypeIsFragment.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "match/fragment-type/is-fragment"))
	}
	if !data.MatchFragmentTypeFirstFragment.IsNull() && !data.MatchFragmentTypeFirstFragment.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "match/fragment-type/first-fragment"))
	}
	if !data.MatchFragmentTypeDontFragment.IsNull() && !data.MatchFragmentTypeDontFragment.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "match/fragment-type/dont-fragment"))
	}
	for i := range data.MatchDestinationAddressIpv6 {
		keys := [...]string{"address", "prefix-length"}
		keyValues := [...]string{data.MatchDestinationAddressIpv6[i].Address.ValueString(), strconv.FormatInt(data.MatchDestinationAddressIpv6[i].PrefixLength.ValueInt64(), 10)}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
	}
	for i := range data.MatchDestinationAddressIpv4 {
		keys := [...]string{"address", "netmask"}
		keyValues := [...]string{data.MatchDestinationAddressIpv4[i].Address.ValueString(), data.MatchDestinationAddressIpv4[i].Netmask.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
	}
	if !data.MatchAny.IsNull() && !data.MatchAny.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "match-any"))
	}
	if !data.MatchAll.IsNull() && !data.MatchAll.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "match-all"))
	}
	return emptyLeafsDelete
}

// End of section. //template:end getEmptyLeafsDelete

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletePaths
func (data *ClassMapTraffic) getDeletePaths(ctx context.Context, version string) []string {
	var deletePaths []string
	if !data.MatchVlanInner.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/vlan-inner/vlan-id"))
	}
	if !data.MatchVlan.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/vlan/vlan-id"))
	}
	if !data.MatchTcpFlagAny.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/tcp-flag/any"))
	}
	if !data.MatchTcpFlag.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/tcp-flag/value"))
	}
	if !data.MatchSourcePort.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/source-port/number"))
	}
	if !data.MatchSourceMac.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/source-address/mac"))
	}
	for i := range data.MatchSourceAddressIpv6 {
		keys := [...]string{"address", "prefix-length"}
		keyValues := [...]string{data.MatchSourceAddressIpv6[i].Address.ValueString(), strconv.FormatInt(data.MatchSourceAddressIpv6[i].PrefixLength.ValueInt64(), 10)}

		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(data.MatchSourceAddressIpv6[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(data.MatchSourceAddressIpv6[i].PrefixLength.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}
		deletePaths = append(deletePaths, fmt.Sprintf("%v/%v%v", data.getPath(), "match/source-address/ipv6/address-prefix", keyString))
	}
	for i := range data.MatchSourceAddressIpv4 {
		keys := [...]string{"address", "netmask"}
		keyValues := [...]string{data.MatchSourceAddressIpv4[i].Address.ValueString(), data.MatchSourceAddressIpv4[i].Netmask.ValueString()}

		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(data.MatchSourceAddressIpv4[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(data.MatchSourceAddressIpv4[i].Netmask.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}
		deletePaths = append(deletePaths, fmt.Sprintf("%v/%v%v", data.getPath(), "match/source-address/ipv4/address-prefix", keyString))
	}
	if !data.MatchProtocol.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/protocol/number"))
	}
	if !data.MatchPrecedenceIpv6.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/precedence-ipv6/value"))
	}
	if !data.MatchPrecedenceIpv4.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/precedence-ipv4/value"))
	}
	if !data.MatchPrecedence.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/precedence/value"))
	}
	if !data.MatchPacketLength.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/packet/length/value"))
	}
	if !data.MatchMplsExperimentalTopmost.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/mpls/experimental/topmost/label"))
	}
	if !data.MatchIpv6IcmpType.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/ipv6/icmp-type/value"))
	}
	if !data.MatchIpv6IcmpCode.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/ipv6/icmp-code/value"))
	}
	if !data.MatchIpv4IcmpType.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/ipv4/icmp-type/value"))
	}
	if !data.MatchIpv4IcmpCode.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/ipv4/icmp-code/value"))
	}
	if !data.MatchFragmentTypeLastFragment.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/fragment-type/last-fragment"))
	}
	if !data.MatchFragmentTypeIsFragment.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/fragment-type/is-fragment"))
	}
	if !data.MatchFragmentTypeFirstFragment.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/fragment-type/first-fragment"))
	}
	if !data.MatchFragmentTypeDontFragment.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/fragment-type/dont-fragment"))
	}
	if !data.MatchFlowTag.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/flow-tag/tag-number"))
	}
	if !data.MatchEthertype.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/ethertype/value"))
	}
	if !data.MatchDscpIpv6.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/dscp-ipv6/value"))
	}
	if !data.MatchDscpIpv4.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/dscp-ipv4/value"))
	}
	if !data.MatchDscp.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/dscp/value"))
	}
	if !data.MatchDestinationPort.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/destination-port/port-number"))
	}
	if !data.MatchDestinationMac.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/destination-address/mac"))
	}
	for i := range data.MatchDestinationAddressIpv6 {
		keys := [...]string{"address", "prefix-length"}
		keyValues := [...]string{data.MatchDestinationAddressIpv6[i].Address.ValueString(), strconv.FormatInt(data.MatchDestinationAddressIpv6[i].PrefixLength.ValueInt64(), 10)}

		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(data.MatchDestinationAddressIpv6[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(data.MatchDestinationAddressIpv6[i].PrefixLength.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}
		deletePaths = append(deletePaths, fmt.Sprintf("%v/%v%v", data.getPath(), "match/destination-address/ipv6/address-prefix", keyString))
	}
	for i := range data.MatchDestinationAddressIpv4 {
		keys := [...]string{"address", "netmask"}
		keyValues := [...]string{data.MatchDestinationAddressIpv4[i].Address.ValueString(), data.MatchDestinationAddressIpv4[i].Netmask.ValueString()}

		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(data.MatchDestinationAddressIpv4[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(data.MatchDestinationAddressIpv4[i].Netmask.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}
		deletePaths = append(deletePaths, fmt.Sprintf("%v/%v%v", data.getPath(), "match/destination-address/ipv4/address-prefix", keyString))
	}
	if !data.MatchCosInner.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/cos-inner/value"))
	}
	if !data.MatchCos.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/cos/value"))
	}
	if !data.MatchAccessGroupIpv6.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/access-group/ipv6"))
	}
	if !data.MatchAccessGroupIpv4.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match/access-group/ipv4"))
	}
	if !data.Description.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "description"))
	}
	if !data.MatchAny.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match-any"))
	}
	if !data.MatchAll.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "match-all"))
	}
	return deletePaths
}

// End of section. //template:end getDeletePaths
