// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxr/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type MPLSTrafficEng struct {
	Device                           types.String `tfsdk:"device"`
	Id                               types.String `tfsdk:"id"`
	DeleteMode                       types.String `tfsdk:"delete_mode"`
	TrafficEng                       types.Bool   `tfsdk:"traffic_eng"`
	Disable                          types.Bool   `tfsdk:"disable"`
	ReoptimizeReoptimizationPeriodIn types.Int64  `tfsdk:"reoptimize_reoptimization_period_in"`
	ServerIpv4                       types.String `tfsdk:"server_ipv4"`
}

type MPLSTrafficEngData struct {
	Device                           types.String `tfsdk:"device"`
	Id                               types.String `tfsdk:"id"`
	TrafficEng                       types.Bool   `tfsdk:"traffic_eng"`
	Disable                          types.Bool   `tfsdk:"disable"`
	ReoptimizeReoptimizationPeriodIn types.Int64  `tfsdk:"reoptimize_reoptimization_period_in"`
	ServerIpv4                       types.String `tfsdk:"server_ipv4"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data MPLSTrafficEng) getPath() string {
	return "Cisco-IOS-XR-um-mpls-te-cfg:/mpls"
}

func (data MPLSTrafficEngData) getPath() string {
	return "Cisco-IOS-XR-um-mpls-te-cfg:/mpls"
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data MPLSTrafficEng) toBody(ctx context.Context, providerVersion string) string {
	body := "{}"
	if !data.TrafficEng.IsNull() && !data.TrafficEng.IsUnknown() {
		if data.TrafficEng.ValueBool() {
			body, _ = sjson.Set(body, "traffic-eng", map[string]string{})
		}
	}
	if helpers.VersionAtLeast(providerVersion, "25.4") {
		if !data.Disable.IsNull() && !data.Disable.IsUnknown() {
			if data.Disable.ValueBool() {
				body, _ = sjson.Set(body, "traffic-eng.pce.reoptimize.disable", map[string]string{})
			}
		}
	}
	if helpers.VersionAtLeast(providerVersion, "25.4") {
		if !data.ReoptimizeReoptimizationPeriodIn.IsNull() && !data.ReoptimizeReoptimizationPeriodIn.IsUnknown() {
			body, _ = sjson.Set(body, "traffic-eng.pce.reoptimize.reoptimization-period-in", strconv.FormatInt(data.ReoptimizeReoptimizationPeriodIn.ValueInt64(), 10))
		}
	}
	if helpers.VersionAtLeast(providerVersion, "25.4") {
		if !data.ServerIpv4.IsNull() && !data.ServerIpv4.IsUnknown() {
			body, _ = sjson.Set(body, "traffic-eng.pce.server.ipv4", data.ServerIpv4.ValueString())
		}
	}
	return body
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin getVersionConstraints

// GetVersionConstraints returns the version constraints for all fields
func (data MPLSTrafficEng) GetVersionConstraints() []helpers.FieldVersionConstraint {
	constraints := make([]helpers.FieldVersionConstraint, 0)

	constraints = append(constraints, []helpers.FieldVersionConstraint{
		{
			FieldPath:      "disable",
			AddedInVersion: "25.4",
		},
		{
			FieldPath:      "reoptimize_reoptimization_period_in",
			AddedInVersion: "25.4",
		},
		{
			FieldPath:      "server_ipv4",
			AddedInVersion: "25.4",
		},
	}...)
	if len(constraints) == 0 {
		return nil
	}
	return constraints
}

// End of section. //template:end getVersionConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getRangeConstraints

// GetRangeConstraints returns the version-specific range constraints for integer fields
func (data MPLSTrafficEng) GetRangeConstraints() []helpers.FieldRangeConstraint {
	return nil
}

// End of section. //template:end getRangeConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody
func (data *MPLSTrafficEng) updateFromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "traffic-eng"); !data.TrafficEng.IsNull() {
		if value.Exists() {
			data.TrafficEng = types.BoolValue(true)
		} else {
			data.TrafficEng = types.BoolValue(false)
		}
	} else {
		data.TrafficEng = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "traffic-eng.pce.reoptimize.disable"); helpers.VersionAtLeast(version, "25.4") && !data.Disable.IsNull() {
		if value.Exists() {
			data.Disable = types.BoolValue(true)
		} else {
			data.Disable = types.BoolValue(false)
		}
	} else {
		data.Disable = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "traffic-eng.pce.reoptimize.reoptimization-period-in"); helpers.VersionAtLeast(version, "25.4") && value.Exists() && value.Type == gjson.Number && !data.ReoptimizeReoptimizationPeriodIn.IsNull() {
		data.ReoptimizeReoptimizationPeriodIn = types.Int64Value(value.Int())
	} else {
		data.ReoptimizeReoptimizationPeriodIn = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "traffic-eng.pce.server.ipv4"); helpers.VersionAtLeast(version, "25.4") && value.Exists() && value.Type == gjson.String && !data.ServerIpv4.IsNull() {
		data.ServerIpv4 = types.StringValue(value.String())
	} else {
		data.ServerIpv4 = types.StringNull()
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *MPLSTrafficEng) fromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "traffic-eng"); value.Exists() {
		data.TrafficEng = types.BoolValue(true)
	} else {
		data.TrafficEng = types.BoolValue(false)
	}
	if helpers.VersionAtLeast(version, "25.4") {
		if value := gjson.GetBytes(res, "traffic-eng.pce.reoptimize.disable"); value.Exists() {
			data.Disable = types.BoolValue(true)
		} else {
			data.Disable = types.BoolValue(false)
		}
	} else {
		data.Disable = types.BoolNull()
	}
	if helpers.VersionAtLeast(version, "25.4") {
		if value := gjson.GetBytes(res, "traffic-eng.pce.reoptimize.reoptimization-period-in"); value.Exists() && value.Type == gjson.Number {
			data.ReoptimizeReoptimizationPeriodIn = types.Int64Value(value.Int())
		}
	} else {
		data.ReoptimizeReoptimizationPeriodIn = types.Int64Null()
	}
	if helpers.VersionAtLeast(version, "25.4") {
		if value := gjson.GetBytes(res, "traffic-eng.pce.server.ipv4"); value.Exists() && value.Type == gjson.String {
			data.ServerIpv4 = types.StringValue(value.String())
		}
	} else {
		data.ServerIpv4 = types.StringNull()
	}
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyData

func (data *MPLSTrafficEngData) fromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "traffic-eng"); value.Exists() {
		data.TrafficEng = types.BoolValue(true)
	} else {
		data.TrafficEng = types.BoolValue(false)
	}
	if helpers.VersionAtLeast(version, "25.4") {
		if value := gjson.GetBytes(res, "traffic-eng.pce.reoptimize.disable"); value.Exists() {
			data.Disable = types.BoolValue(true)
		} else {
			data.Disable = types.BoolValue(false)
		}
	} else {
		data.Disable = types.BoolNull()
	}
	if helpers.VersionAtLeast(version, "25.4") {
		if value := gjson.GetBytes(res, "traffic-eng.pce.reoptimize.reoptimization-period-in"); value.Exists() && value.Type == gjson.Number {
			data.ReoptimizeReoptimizationPeriodIn = types.Int64Value(value.Int())
		}
	} else {
		data.ReoptimizeReoptimizationPeriodIn = types.Int64Null()
	}
	if helpers.VersionAtLeast(version, "25.4") {
		if value := gjson.GetBytes(res, "traffic-eng.pce.server.ipv4"); value.Exists() && value.Type == gjson.String {
			data.ServerIpv4 = types.StringValue(value.String())
		}
	} else {
		data.ServerIpv4 = types.StringNull()
	}
}

// End of section. //template:end fromBodyData

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletedItems

func (data *MPLSTrafficEng) getDeletedItems(ctx context.Context, state MPLSTrafficEng, version string) []string {
	deletedItems := make([]string, 0)
	if helpers.VersionAtLeast(version, "25.4") && !state.ServerIpv4.IsNull() && data.ServerIpv4.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/traffic-eng/pce/server/ipv4", state.getPath()))
	}
	if helpers.VersionAtLeast(version, "25.4") && !state.ReoptimizeReoptimizationPeriodIn.IsNull() && data.ReoptimizeReoptimizationPeriodIn.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/traffic-eng/pce/reoptimize/reoptimization-period-in", state.getPath()))
	}
	if helpers.VersionAtLeast(version, "25.4") && !state.Disable.IsNull() && data.Disable.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/traffic-eng/pce/reoptimize/disable", state.getPath()))
	}
	if !state.TrafficEng.IsNull() && data.TrafficEng.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/traffic-eng", state.getPath()))
	}
	return deletedItems
}

// End of section. //template:end getDeletedItems

// Section below is generated&owned by "gen/generator.go". //template:begin getEmptyLeafsDelete

func (data *MPLSTrafficEng) getEmptyLeafsDelete(ctx context.Context, version string) []string {
	emptyLeafsDelete := make([]string, 0)
	if helpers.VersionAtLeast(version, "25.4") && !data.Disable.IsNull() && !data.Disable.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/traffic-eng/pce/reoptimize/disable", data.getPath()))
	}
	if !data.TrafficEng.IsNull() && !data.TrafficEng.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/traffic-eng", data.getPath()))
	}
	return emptyLeafsDelete
}

// End of section. //template:end getEmptyLeafsDelete

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletePaths
func (data *MPLSTrafficEng) getDeletePaths(ctx context.Context, version string) []string {
	var deletePaths []string
	if helpers.VersionAtLeast(version, "25.4") && !data.ServerIpv4.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/traffic-eng/pce/server/ipv4", data.getPath()))
	}
	if helpers.VersionAtLeast(version, "25.4") && !data.ReoptimizeReoptimizationPeriodIn.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/traffic-eng/pce/reoptimize/reoptimization-period-in", data.getPath()))
	}
	if helpers.VersionAtLeast(version, "25.4") && !data.Disable.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/traffic-eng/pce/reoptimize/disable", data.getPath()))
	}
	if !data.TrafficEng.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/traffic-eng", data.getPath()))
	}
	return deletePaths
}

// End of section. //template:end getDeletePaths
