// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"path"
	"reflect"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxr/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type RadiusServer struct {
	Device                                                 types.String                 `tfsdk:"device"`
	Id                                                     types.String                 `tfsdk:"id"`
	DeleteMode                                             types.String                 `tfsdk:"delete_mode"`
	Hosts                                                  []RadiusServerHosts          `tfsdk:"hosts"`
	KeyType7                                               types.String                 `tfsdk:"key_type_7"`
	KeyType6                                               types.String                 `tfsdk:"key_type_6"`
	Timeout                                                types.Int64                  `tfsdk:"timeout"`
	RetransmitRetries                                      types.Int64                  `tfsdk:"retransmit_retries"`
	RetransmitDisable                                      types.Bool                   `tfsdk:"retransmit_disable"`
	LoadBalanceMethodLeastOutstandingBatchSize             types.Int64                  `tfsdk:"load_balance_method_least_outstanding_batch_size"`
	LoadBalanceMethodLeastOutstandingIgnorePreferredServer types.Bool                   `tfsdk:"load_balance_method_least_outstanding_ignore_preferred_server"`
	ThrottleAccess                                         types.Int64                  `tfsdk:"throttle_access"`
	ThrottleAccessTimeout                                  types.Int64                  `tfsdk:"throttle_access_timeout"`
	ThrottleAccounting                                     types.Int64                  `tfsdk:"throttle_accounting"`
	Deadtime                                               types.Int64                  `tfsdk:"deadtime"`
	DeadCriteriaTime                                       types.Int64                  `tfsdk:"dead_criteria_time"`
	DeadCriteriaTries                                      types.Int64                  `tfsdk:"dead_criteria_tries"`
	SourcePortExtended                                     types.Bool                   `tfsdk:"source_port_extended"`
	Ipv4Dscp                                               types.String                 `tfsdk:"ipv4_dscp"`
	Ipv6Dscp                                               types.String                 `tfsdk:"ipv6_dscp"`
	VsaAttributeIgnoreUnknown                              types.Bool                   `tfsdk:"vsa_attribute_ignore_unknown"`
	DisallowNullUsername                                   types.Bool                   `tfsdk:"disallow_null_username"`
	AttributeLists                                         []RadiusServerAttributeLists `tfsdk:"attribute_lists"`
	AttributeAcctSessionIdPrependNasPortId                 types.Bool                   `tfsdk:"attribute_acct_session_id_prepend_nas_port_id"`
	AttributeAcctMultiSessionIdIncludeParentSessionId      types.Bool                   `tfsdk:"attribute_acct_multi_session_id_include_parent_session_id"`
	AttributeFilterId11DefaultDirection                    types.String                 `tfsdk:"attribute_filter_id_11_default_direction"`
}

type RadiusServerData struct {
	Device                                                 types.String                 `tfsdk:"device"`
	Id                                                     types.String                 `tfsdk:"id"`
	Hosts                                                  []RadiusServerHosts          `tfsdk:"hosts"`
	KeyType7                                               types.String                 `tfsdk:"key_type_7"`
	KeyType6                                               types.String                 `tfsdk:"key_type_6"`
	Timeout                                                types.Int64                  `tfsdk:"timeout"`
	RetransmitRetries                                      types.Int64                  `tfsdk:"retransmit_retries"`
	RetransmitDisable                                      types.Bool                   `tfsdk:"retransmit_disable"`
	LoadBalanceMethodLeastOutstandingBatchSize             types.Int64                  `tfsdk:"load_balance_method_least_outstanding_batch_size"`
	LoadBalanceMethodLeastOutstandingIgnorePreferredServer types.Bool                   `tfsdk:"load_balance_method_least_outstanding_ignore_preferred_server"`
	ThrottleAccess                                         types.Int64                  `tfsdk:"throttle_access"`
	ThrottleAccessTimeout                                  types.Int64                  `tfsdk:"throttle_access_timeout"`
	ThrottleAccounting                                     types.Int64                  `tfsdk:"throttle_accounting"`
	Deadtime                                               types.Int64                  `tfsdk:"deadtime"`
	DeadCriteriaTime                                       types.Int64                  `tfsdk:"dead_criteria_time"`
	DeadCriteriaTries                                      types.Int64                  `tfsdk:"dead_criteria_tries"`
	SourcePortExtended                                     types.Bool                   `tfsdk:"source_port_extended"`
	Ipv4Dscp                                               types.String                 `tfsdk:"ipv4_dscp"`
	Ipv6Dscp                                               types.String                 `tfsdk:"ipv6_dscp"`
	VsaAttributeIgnoreUnknown                              types.Bool                   `tfsdk:"vsa_attribute_ignore_unknown"`
	DisallowNullUsername                                   types.Bool                   `tfsdk:"disallow_null_username"`
	AttributeLists                                         []RadiusServerAttributeLists `tfsdk:"attribute_lists"`
	AttributeAcctSessionIdPrependNasPortId                 types.Bool                   `tfsdk:"attribute_acct_session_id_prepend_nas_port_id"`
	AttributeAcctMultiSessionIdIncludeParentSessionId      types.Bool                   `tfsdk:"attribute_acct_multi_session_id_include_parent_session_id"`
	AttributeFilterId11DefaultDirection                    types.String                 `tfsdk:"attribute_filter_id_11_default_direction"`
}
type RadiusServerHosts struct {
	Order                  types.Int64  `tfsdk:"order"`
	Address                types.String `tfsdk:"address"`
	AuthPort               types.Int64  `tfsdk:"auth_port"`
	AcctPort               types.Int64  `tfsdk:"acct_port"`
	Timeout                types.Int64  `tfsdk:"timeout"`
	Retransmit             types.Int64  `tfsdk:"retransmit"`
	KeyType7               types.String `tfsdk:"key_type_7"`
	KeyType6               types.String `tfsdk:"key_type_6"`
	TestUsername           types.String `tfsdk:"test_username"`
	IdleTime               types.Int64  `tfsdk:"idle_time"`
	IgnoreAuthPort         types.Bool   `tfsdk:"ignore_auth_port"`
	IgnoreAcctPort         types.Bool   `tfsdk:"ignore_acct_port"`
	DtlsServerTrustpoint   types.String `tfsdk:"dtls_server_trustpoint"`
	RadsecServerTrustpoint types.String `tfsdk:"radsec_server_trustpoint"`
}
type RadiusServerAttributeLists struct {
	Name               types.String                                   `tfsdk:"name"`
	RadiusAttributes   types.String                                   `tfsdk:"radius_attributes"`
	AttributeVendorIds []RadiusServerAttributeListsAttributeVendorIds `tfsdk:"attribute_vendor_ids"`
}
type RadiusServerAttributeListsAttributeVendorIds struct {
	Id          types.Int64                                               `tfsdk:"id"`
	VendorTypes []RadiusServerAttributeListsAttributeVendorIdsVendorTypes `tfsdk:"vendor_types"`
}
type RadiusServerAttributeListsAttributeVendorIdsVendorTypes struct {
	VendorTypeId types.Int64 `tfsdk:"vendor_type_id"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data RadiusServer) getPath() string {
	return "Cisco-IOS-XR-um-aaa-cfg:/aaa/Cisco-IOS-XR-um-aaa-radius-server-cfg:radius-server"
}

func (data RadiusServerData) getPath() string {
	return "Cisco-IOS-XR-um-aaa-cfg:/aaa/Cisco-IOS-XR-um-aaa-radius-server-cfg:radius-server"
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data RadiusServer) toBody(ctx context.Context, providerVersion string) string {
	body := "{}"
	if !data.KeyType7.IsNull() && !data.KeyType7.IsUnknown() {
		body, _ = sjson.Set(body, "key.seven", data.KeyType7.ValueString())
	}
	if !data.KeyType6.IsNull() && !data.KeyType6.IsUnknown() {
		body, _ = sjson.Set(body, "key.six", data.KeyType6.ValueString())
	}
	if !data.Timeout.IsNull() && !data.Timeout.IsUnknown() {
		body, _ = sjson.Set(body, "timeout", strconv.FormatInt(data.Timeout.ValueInt64(), 10))
	}
	if !data.RetransmitRetries.IsNull() && !data.RetransmitRetries.IsUnknown() {
		body, _ = sjson.Set(body, "retransmit.retries", strconv.FormatInt(data.RetransmitRetries.ValueInt64(), 10))
	}
	if !data.RetransmitDisable.IsNull() && !data.RetransmitDisable.IsUnknown() {
		if data.RetransmitDisable.ValueBool() {
			body, _ = sjson.Set(body, "retransmit.disable", map[string]string{})
		}
	}
	if !data.LoadBalanceMethodLeastOutstandingBatchSize.IsNull() && !data.LoadBalanceMethodLeastOutstandingBatchSize.IsUnknown() {
		body, _ = sjson.Set(body, "load-balance.method.least-outstanding.batch-size", strconv.FormatInt(data.LoadBalanceMethodLeastOutstandingBatchSize.ValueInt64(), 10))
	}
	if !data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer.IsNull() && !data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer.IsUnknown() {
		if data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer.ValueBool() {
			body, _ = sjson.Set(body, "load-balance.method.least-outstanding.ignore-preferred-server", map[string]string{})
		}
	}
	if !data.ThrottleAccess.IsNull() && !data.ThrottleAccess.IsUnknown() {
		body, _ = sjson.Set(body, "throttle.access", strconv.FormatInt(data.ThrottleAccess.ValueInt64(), 10))
	}
	if !data.ThrottleAccessTimeout.IsNull() && !data.ThrottleAccessTimeout.IsUnknown() {
		body, _ = sjson.Set(body, "throttle.access-timeout", strconv.FormatInt(data.ThrottleAccessTimeout.ValueInt64(), 10))
	}
	if !data.ThrottleAccounting.IsNull() && !data.ThrottleAccounting.IsUnknown() {
		body, _ = sjson.Set(body, "throttle.accounting", strconv.FormatInt(data.ThrottleAccounting.ValueInt64(), 10))
	}
	if !data.Deadtime.IsNull() && !data.Deadtime.IsUnknown() {
		body, _ = sjson.Set(body, "deadtime", strconv.FormatInt(data.Deadtime.ValueInt64(), 10))
	}
	if !data.DeadCriteriaTime.IsNull() && !data.DeadCriteriaTime.IsUnknown() {
		body, _ = sjson.Set(body, "dead-criteria.time", strconv.FormatInt(data.DeadCriteriaTime.ValueInt64(), 10))
	}
	if !data.DeadCriteriaTries.IsNull() && !data.DeadCriteriaTries.IsUnknown() {
		body, _ = sjson.Set(body, "dead-criteria.tries", strconv.FormatInt(data.DeadCriteriaTries.ValueInt64(), 10))
	}
	if !data.SourcePortExtended.IsNull() && !data.SourcePortExtended.IsUnknown() {
		if data.SourcePortExtended.ValueBool() {
			body, _ = sjson.Set(body, "source-port.extended", map[string]string{})
		}
	}
	if !data.Ipv4Dscp.IsNull() && !data.Ipv4Dscp.IsUnknown() {
		body, _ = sjson.Set(body, "ipv4.dscp", data.Ipv4Dscp.ValueString())
	}
	if !data.Ipv6Dscp.IsNull() && !data.Ipv6Dscp.IsUnknown() {
		body, _ = sjson.Set(body, "ipv6.dscp", data.Ipv6Dscp.ValueString())
	}
	if !data.VsaAttributeIgnoreUnknown.IsNull() && !data.VsaAttributeIgnoreUnknown.IsUnknown() {
		if data.VsaAttributeIgnoreUnknown.ValueBool() {
			body, _ = sjson.Set(body, "vsa.attribute.ignore.unknown", map[string]string{})
		}
	}
	if !data.DisallowNullUsername.IsNull() && !data.DisallowNullUsername.IsUnknown() {
		if data.DisallowNullUsername.ValueBool() {
			body, _ = sjson.Set(body, "disallow.null-username", map[string]string{})
		}
	}
	if !data.AttributeAcctSessionIdPrependNasPortId.IsNull() && !data.AttributeAcctSessionIdPrependNasPortId.IsUnknown() {
		if data.AttributeAcctSessionIdPrependNasPortId.ValueBool() {
			body, _ = sjson.Set(body, "attribute.acct-session-id.prepend-nas-port-id", map[string]string{})
		}
	}
	if !data.AttributeAcctMultiSessionIdIncludeParentSessionId.IsNull() && !data.AttributeAcctMultiSessionIdIncludeParentSessionId.IsUnknown() {
		if data.AttributeAcctMultiSessionIdIncludeParentSessionId.ValueBool() {
			body, _ = sjson.Set(body, "attribute.acct-multi-session-id.include-parent-session-id", map[string]string{})
		}
	}
	if !data.AttributeFilterId11DefaultDirection.IsNull() && !data.AttributeFilterId11DefaultDirection.IsUnknown() {
		body, _ = sjson.Set(body, "attribute.filter-id-11.default.direction", data.AttributeFilterId11DefaultDirection.ValueString())
	}
	if len(data.Hosts) > 0 {
		body, _ = sjson.Set(body, "hosts.host", []interface{}{})
		for index, item := range data.Hosts {
			if !item.Order.IsNull() && !item.Order.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"ordering-index", strconv.FormatInt(item.Order.ValueInt64(), 10))
			}
			if !item.Address.IsNull() && !item.Address.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"address", item.Address.ValueString())
			}
			if !item.AuthPort.IsNull() && !item.AuthPort.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"auth-port", strconv.FormatInt(item.AuthPort.ValueInt64(), 10))
			}
			if !item.AcctPort.IsNull() && !item.AcctPort.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"acct-port", strconv.FormatInt(item.AcctPort.ValueInt64(), 10))
			}
			if !item.Timeout.IsNull() && !item.Timeout.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"timeout", strconv.FormatInt(item.Timeout.ValueInt64(), 10))
			}
			if !item.Retransmit.IsNull() && !item.Retransmit.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"retransmit", strconv.FormatInt(item.Retransmit.ValueInt64(), 10))
			}
			if !item.KeyType7.IsNull() && !item.KeyType7.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"key.seven", item.KeyType7.ValueString())
			}
			if !item.KeyType6.IsNull() && !item.KeyType6.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"key.six", item.KeyType6.ValueString())
			}
			if !item.TestUsername.IsNull() && !item.TestUsername.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"test.username", item.TestUsername.ValueString())
			}
			if !item.IdleTime.IsNull() && !item.IdleTime.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"idle-time", strconv.FormatInt(item.IdleTime.ValueInt64(), 10))
			}
			if !item.IgnoreAuthPort.IsNull() && !item.IgnoreAuthPort.IsUnknown() {
				if item.IgnoreAuthPort.ValueBool() {
					body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"ignore-auth-port", map[string]string{})
				}
			}
			if !item.IgnoreAcctPort.IsNull() && !item.IgnoreAcctPort.IsUnknown() {
				if item.IgnoreAcctPort.ValueBool() {
					body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"ignore-acct-port", map[string]string{})
				}
			}
			if !item.DtlsServerTrustpoint.IsNull() && !item.DtlsServerTrustpoint.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"dtls-server.trustpoint", item.DtlsServerTrustpoint.ValueString())
			}
			if !item.RadsecServerTrustpoint.IsNull() && !item.RadsecServerTrustpoint.IsUnknown() {
				body, _ = sjson.Set(body, "hosts.host"+"."+strconv.Itoa(index)+"."+"radsec-server.trustpoint", item.RadsecServerTrustpoint.ValueString())
			}
		}
	}
	if len(data.AttributeLists) > 0 {
		body, _ = sjson.Set(body, "attribute.list", []interface{}{})
		for index, item := range data.AttributeLists {
			if !item.Name.IsNull() && !item.Name.IsUnknown() {
				body, _ = sjson.Set(body, "attribute.list"+"."+strconv.Itoa(index)+"."+"list-name", item.Name.ValueString())
			}
			if !item.RadiusAttributes.IsNull() && !item.RadiusAttributes.IsUnknown() {
				body, _ = sjson.Set(body, "attribute.list"+"."+strconv.Itoa(index)+"."+"attribute.radius-attributes", item.RadiusAttributes.ValueString())
			}
			if len(item.AttributeVendorIds) > 0 {
				body, _ = sjson.Set(body, "attribute.list"+"."+strconv.Itoa(index)+"."+"attribute.vendor-ids.vendor-id", []interface{}{})
				for cindex, citem := range item.AttributeVendorIds {
					if !citem.Id.IsNull() && !citem.Id.IsUnknown() {
						body, _ = sjson.Set(body, "attribute.list"+"."+strconv.Itoa(index)+"."+"attribute.vendor-ids.vendor-id"+"."+strconv.Itoa(cindex)+"."+"id", strconv.FormatInt(citem.Id.ValueInt64(), 10))
					}
					if len(citem.VendorTypes) > 0 {
						body, _ = sjson.Set(body, "attribute.list"+"."+strconv.Itoa(index)+"."+"attribute.vendor-ids.vendor-id"+"."+strconv.Itoa(cindex)+"."+"vendor-types.vendor-type", []interface{}{})
						for ccindex, ccitem := range citem.VendorTypes {
							if !ccitem.VendorTypeId.IsNull() && !ccitem.VendorTypeId.IsUnknown() {
								body, _ = sjson.Set(body, "attribute.list"+"."+strconv.Itoa(index)+"."+"attribute.vendor-ids.vendor-id"+"."+strconv.Itoa(cindex)+"."+"vendor-types.vendor-type"+"."+strconv.Itoa(ccindex)+"."+"vendor-type-id", strconv.FormatInt(ccitem.VendorTypeId.ValueInt64(), 10))
							}
						}
					}
				}
			}
		}
	}
	return body
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin getVersionConstraints

// GetVersionConstraints returns the version constraints for all fields
func (data RadiusServer) GetVersionConstraints() []helpers.FieldVersionConstraint {
	constraints := make([]helpers.FieldVersionConstraint, 0)

	if len(constraints) == 0 {
		return nil
	}
	return constraints
}

// End of section. //template:end getVersionConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getRangeConstraints

// GetRangeConstraints returns the version-specific range constraints for integer fields
func (data RadiusServer) GetRangeConstraints() []helpers.FieldRangeConstraint {
	return nil
}

// End of section. //template:end getRangeConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getEnumConstraints

// GetEnumConstraints returns the version-specific enum constraints for string fields
func (data RadiusServer) GetEnumConstraints() []helpers.FieldEnumConstraint {
	return nil
}

// End of section. //template:end getEnumConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getStringLengthConstraints

// GetStringLengthConstraints returns the version-specific string length constraints
func (data RadiusServer) GetStringLengthConstraints() []helpers.FieldStringLengthConstraint {
	return nil
}

// End of section. //template:end getStringLengthConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getPatternConstraints

// GetPatternConstraints returns the version-specific string pattern constraints
func (data RadiusServer) GetPatternConstraints() []helpers.FieldPatternConstraint {
	return nil
}

// End of section. //template:end getPatternConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getDefaultConstraints
// End of section. //template:end getDefaultConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody
func (data *RadiusServer) updateFromBody(ctx context.Context, res []byte, version string) {
	for i := range data.Hosts {
		keys := [...]string{"ordering-index", "address", "auth-port", "acct-port"}
		keyValues := [...]string{strconv.FormatInt(data.Hosts[i].Order.ValueInt64(), 10), data.Hosts[i].Address.ValueString(), strconv.FormatInt(data.Hosts[i].AuthPort.ValueInt64(), 10), strconv.FormatInt(data.Hosts[i].AcctPort.ValueInt64(), 10)}

		var r gjson.Result
		gjson.GetBytes(res, "hosts.host").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("ordering-index"); value.Exists() && value.Type == gjson.Number && !data.Hosts[i].Order.IsNull() {
			data.Hosts[i].Order = types.Int64Value(value.Int())
		} else {
			data.Hosts[i].Order = types.Int64Null()
		}
		if value := r.Get("address"); value.Exists() && value.Type == gjson.String && !data.Hosts[i].Address.IsNull() {
			data.Hosts[i].Address = types.StringValue(value.String())
		} else {
			data.Hosts[i].Address = types.StringNull()
		}
		if value := r.Get("auth-port"); value.Exists() && value.Type == gjson.Number && !data.Hosts[i].AuthPort.IsNull() {
			data.Hosts[i].AuthPort = types.Int64Value(value.Int())
		} else {
			data.Hosts[i].AuthPort = types.Int64Null()
		}
		if value := r.Get("acct-port"); value.Exists() && value.Type == gjson.Number && !data.Hosts[i].AcctPort.IsNull() {
			data.Hosts[i].AcctPort = types.Int64Value(value.Int())
		} else {
			data.Hosts[i].AcctPort = types.Int64Null()
		}
		if value := r.Get("timeout"); value.Exists() && value.Type == gjson.Number && !data.Hosts[i].Timeout.IsNull() {
			data.Hosts[i].Timeout = types.Int64Value(value.Int())
		} else {
			data.Hosts[i].Timeout = types.Int64Null()
		}
		if value := r.Get("retransmit"); value.Exists() && value.Type == gjson.Number && !data.Hosts[i].Retransmit.IsNull() {
			data.Hosts[i].Retransmit = types.Int64Value(value.Int())
		} else {
			data.Hosts[i].Retransmit = types.Int64Null()
		}
		if value := r.Get("test.username"); value.Exists() && value.Type == gjson.String && !data.Hosts[i].TestUsername.IsNull() {
			data.Hosts[i].TestUsername = types.StringValue(value.String())
		} else {
			data.Hosts[i].TestUsername = types.StringNull()
		}
		if value := r.Get("idle-time"); value.Exists() && value.Type == gjson.Number && !data.Hosts[i].IdleTime.IsNull() {
			data.Hosts[i].IdleTime = types.Int64Value(value.Int())
		} else {
			data.Hosts[i].IdleTime = types.Int64Null()
		}
		if value := r.Get("ignore-auth-port"); !data.Hosts[i].IgnoreAuthPort.IsNull() {
			if value.Exists() {
				data.Hosts[i].IgnoreAuthPort = types.BoolValue(true)
			} else {
				data.Hosts[i].IgnoreAuthPort = types.BoolValue(false)
			}
		} else {
			data.Hosts[i].IgnoreAuthPort = types.BoolNull()
		}
		if value := r.Get("ignore-acct-port"); !data.Hosts[i].IgnoreAcctPort.IsNull() {
			if value.Exists() {
				data.Hosts[i].IgnoreAcctPort = types.BoolValue(true)
			} else {
				data.Hosts[i].IgnoreAcctPort = types.BoolValue(false)
			}
		} else {
			data.Hosts[i].IgnoreAcctPort = types.BoolNull()
		}
		if value := r.Get("dtls-server.trustpoint"); value.Exists() && value.Type == gjson.String && !data.Hosts[i].DtlsServerTrustpoint.IsNull() {
			data.Hosts[i].DtlsServerTrustpoint = types.StringValue(value.String())
		} else {
			data.Hosts[i].DtlsServerTrustpoint = types.StringNull()
		}
		if value := r.Get("radsec-server.trustpoint"); value.Exists() && value.Type == gjson.String && !data.Hosts[i].RadsecServerTrustpoint.IsNull() {
			data.Hosts[i].RadsecServerTrustpoint = types.StringValue(value.String())
		} else {
			data.Hosts[i].RadsecServerTrustpoint = types.StringNull()
		}
	}
	if value := gjson.GetBytes(res, "timeout"); value.Exists() && value.Type == gjson.Number && !data.Timeout.IsNull() {
		data.Timeout = types.Int64Value(value.Int())
	} else {
		data.Timeout = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "retransmit.retries"); value.Exists() && value.Type == gjson.Number && !data.RetransmitRetries.IsNull() {
		data.RetransmitRetries = types.Int64Value(value.Int())
	} else {
		data.RetransmitRetries = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "retransmit.disable"); !data.RetransmitDisable.IsNull() {
		if value.Exists() {
			data.RetransmitDisable = types.BoolValue(true)
		} else {
			data.RetransmitDisable = types.BoolValue(false)
		}
	} else {
		data.RetransmitDisable = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "load-balance.method.least-outstanding.batch-size"); value.Exists() && value.Type == gjson.Number && !data.LoadBalanceMethodLeastOutstandingBatchSize.IsNull() {
		data.LoadBalanceMethodLeastOutstandingBatchSize = types.Int64Value(value.Int())
	} else {
		data.LoadBalanceMethodLeastOutstandingBatchSize = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "load-balance.method.least-outstanding.ignore-preferred-server"); !data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer.IsNull() {
		if value.Exists() {
			data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer = types.BoolValue(true)
		} else {
			data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer = types.BoolValue(false)
		}
	} else {
		data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "throttle.access"); value.Exists() && value.Type == gjson.Number && !data.ThrottleAccess.IsNull() {
		data.ThrottleAccess = types.Int64Value(value.Int())
	} else {
		data.ThrottleAccess = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "throttle.access-timeout"); value.Exists() && value.Type == gjson.Number && !data.ThrottleAccessTimeout.IsNull() {
		data.ThrottleAccessTimeout = types.Int64Value(value.Int())
	} else {
		data.ThrottleAccessTimeout = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "throttle.accounting"); value.Exists() && value.Type == gjson.Number && !data.ThrottleAccounting.IsNull() {
		data.ThrottleAccounting = types.Int64Value(value.Int())
	} else {
		data.ThrottleAccounting = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "deadtime"); value.Exists() && value.Type == gjson.Number && !data.Deadtime.IsNull() {
		data.Deadtime = types.Int64Value(value.Int())
	} else {
		data.Deadtime = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "dead-criteria.time"); value.Exists() && value.Type == gjson.Number && !data.DeadCriteriaTime.IsNull() {
		data.DeadCriteriaTime = types.Int64Value(value.Int())
	} else {
		data.DeadCriteriaTime = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "dead-criteria.tries"); value.Exists() && value.Type == gjson.Number && !data.DeadCriteriaTries.IsNull() {
		data.DeadCriteriaTries = types.Int64Value(value.Int())
	} else {
		data.DeadCriteriaTries = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "source-port.extended"); !data.SourcePortExtended.IsNull() {
		if value.Exists() {
			data.SourcePortExtended = types.BoolValue(true)
		} else {
			data.SourcePortExtended = types.BoolValue(false)
		}
	} else {
		data.SourcePortExtended = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "ipv4.dscp"); value.Exists() && value.Type == gjson.String && !data.Ipv4Dscp.IsNull() {
		data.Ipv4Dscp = types.StringValue(value.String())
	} else {
		data.Ipv4Dscp = types.StringNull()
	}
	if value := gjson.GetBytes(res, "ipv6.dscp"); value.Exists() && value.Type == gjson.String && !data.Ipv6Dscp.IsNull() {
		data.Ipv6Dscp = types.StringValue(value.String())
	} else {
		data.Ipv6Dscp = types.StringNull()
	}
	if value := gjson.GetBytes(res, "vsa.attribute.ignore.unknown"); !data.VsaAttributeIgnoreUnknown.IsNull() {
		if value.Exists() {
			data.VsaAttributeIgnoreUnknown = types.BoolValue(true)
		} else {
			data.VsaAttributeIgnoreUnknown = types.BoolValue(false)
		}
	} else {
		data.VsaAttributeIgnoreUnknown = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "disallow.null-username"); !data.DisallowNullUsername.IsNull() {
		if value.Exists() {
			data.DisallowNullUsername = types.BoolValue(true)
		} else {
			data.DisallowNullUsername = types.BoolValue(false)
		}
	} else {
		data.DisallowNullUsername = types.BoolNull()
	}
	for i := range data.AttributeLists {
		keys := [...]string{"list-name"}
		keyValues := [...]string{data.AttributeLists[i].Name.ValueString()}

		var r gjson.Result
		gjson.GetBytes(res, "attribute.list").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("list-name"); value.Exists() && value.Type == gjson.String && !data.AttributeLists[i].Name.IsNull() {
			data.AttributeLists[i].Name = types.StringValue(value.String())
		} else {
			data.AttributeLists[i].Name = types.StringNull()
		}
		if value := r.Get("attribute.radius-attributes"); value.Exists() && value.Type == gjson.String && !data.AttributeLists[i].RadiusAttributes.IsNull() {
			data.AttributeLists[i].RadiusAttributes = types.StringValue(value.String())
		} else {
			data.AttributeLists[i].RadiusAttributes = types.StringNull()
		}
		for ci := range data.AttributeLists[i].AttributeVendorIds {
			keys := [...]string{"id"}
			keyValues := [...]string{strconv.FormatInt(data.AttributeLists[i].AttributeVendorIds[ci].Id.ValueInt64(), 10)}

			var cr gjson.Result
			r.Get("attribute.vendor-ids.vendor-id").ForEach(
				func(_, v gjson.Result) bool {
					found := false
					for ik := range keys {
						if v.Get(keys[ik]).String() == keyValues[ik] {
							found = true
							continue
						}
						found = false
						break
					}
					if found {
						cr = v
						return false
					}
					return true
				},
			)
			if value := cr.Get("id"); value.Exists() && value.Type == gjson.Number && !data.AttributeLists[i].AttributeVendorIds[ci].Id.IsNull() {
				data.AttributeLists[i].AttributeVendorIds[ci].Id = types.Int64Value(value.Int())
			} else {
				data.AttributeLists[i].AttributeVendorIds[ci].Id = types.Int64Null()
			}
			for cci := range data.AttributeLists[i].AttributeVendorIds[ci].VendorTypes {
				keys := [...]string{"vendor-type-id"}
				keyValues := [...]string{strconv.FormatInt(data.AttributeLists[i].AttributeVendorIds[ci].VendorTypes[cci].VendorTypeId.ValueInt64(), 10)}

				var ccr gjson.Result
				cr.Get("vendor-types.vendor-type").ForEach(
					func(_, v gjson.Result) bool {
						found := false
						for ik := range keys {
							if v.Get(keys[ik]).String() == keyValues[ik] {
								found = true
								continue
							}
							found = false
							break
						}
						if found {
							ccr = v
							return false
						}
						return true
					},
				)
				if value := ccr.Get("vendor-type-id"); value.Exists() && value.Type == gjson.Number && !data.AttributeLists[i].AttributeVendorIds[ci].VendorTypes[cci].VendorTypeId.IsNull() {
					data.AttributeLists[i].AttributeVendorIds[ci].VendorTypes[cci].VendorTypeId = types.Int64Value(value.Int())
				} else {
					data.AttributeLists[i].AttributeVendorIds[ci].VendorTypes[cci].VendorTypeId = types.Int64Null()
				}
			}
		}
	}
	if value := gjson.GetBytes(res, "attribute.acct-session-id.prepend-nas-port-id"); !data.AttributeAcctSessionIdPrependNasPortId.IsNull() {
		if value.Exists() {
			data.AttributeAcctSessionIdPrependNasPortId = types.BoolValue(true)
		} else {
			data.AttributeAcctSessionIdPrependNasPortId = types.BoolValue(false)
		}
	} else {
		data.AttributeAcctSessionIdPrependNasPortId = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "attribute.acct-multi-session-id.include-parent-session-id"); !data.AttributeAcctMultiSessionIdIncludeParentSessionId.IsNull() {
		if value.Exists() {
			data.AttributeAcctMultiSessionIdIncludeParentSessionId = types.BoolValue(true)
		} else {
			data.AttributeAcctMultiSessionIdIncludeParentSessionId = types.BoolValue(false)
		}
	} else {
		data.AttributeAcctMultiSessionIdIncludeParentSessionId = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "attribute.filter-id-11.default.direction"); value.Exists() && value.Type == gjson.String && !data.AttributeFilterId11DefaultDirection.IsNull() {
		data.AttributeFilterId11DefaultDirection = types.StringValue(value.String())
	} else {
		data.AttributeFilterId11DefaultDirection = types.StringNull()
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *RadiusServer) fromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "hosts.host"); value.Exists() {
		data.Hosts = make([]RadiusServerHosts, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := RadiusServerHosts{}
			if cValue := v.Get("ordering-index"); cValue.Exists() && cValue.Type == gjson.Number {
				item.Order = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("address"); cValue.Exists() && cValue.Type == gjson.String {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := v.Get("auth-port"); cValue.Exists() && cValue.Type == gjson.Number {
				item.AuthPort = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("acct-port"); cValue.Exists() && cValue.Type == gjson.Number {
				item.AcctPort = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("timeout"); cValue.Exists() && cValue.Type == gjson.Number {
				item.Timeout = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("retransmit"); cValue.Exists() && cValue.Type == gjson.Number {
				item.Retransmit = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("test.username"); cValue.Exists() && cValue.Type == gjson.String {
				item.TestUsername = types.StringValue(cValue.String())
			}
			if cValue := v.Get("idle-time"); cValue.Exists() && cValue.Type == gjson.Number {
				item.IdleTime = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("ignore-auth-port"); cValue.Exists() {
				item.IgnoreAuthPort = types.BoolValue(true)
			} else {
				item.IgnoreAuthPort = types.BoolValue(false)
			}
			if cValue := v.Get("ignore-acct-port"); cValue.Exists() {
				item.IgnoreAcctPort = types.BoolValue(true)
			} else {
				item.IgnoreAcctPort = types.BoolValue(false)
			}
			if cValue := v.Get("dtls-server.trustpoint"); cValue.Exists() && cValue.Type == gjson.String {
				item.DtlsServerTrustpoint = types.StringValue(cValue.String())
			}
			if cValue := v.Get("radsec-server.trustpoint"); cValue.Exists() && cValue.Type == gjson.String {
				item.RadsecServerTrustpoint = types.StringValue(cValue.String())
			}
			data.Hosts = append(data.Hosts, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "timeout"); value.Exists() && value.Type == gjson.Number {
		data.Timeout = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "retransmit.retries"); value.Exists() && value.Type == gjson.Number {
		data.RetransmitRetries = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "retransmit.disable"); value.Exists() {
		data.RetransmitDisable = types.BoolValue(true)
	} else {
		data.RetransmitDisable = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "load-balance.method.least-outstanding.batch-size"); value.Exists() && value.Type == gjson.Number {
		data.LoadBalanceMethodLeastOutstandingBatchSize = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "load-balance.method.least-outstanding.ignore-preferred-server"); value.Exists() {
		data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer = types.BoolValue(true)
	} else {
		data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "throttle.access"); value.Exists() && value.Type == gjson.Number {
		data.ThrottleAccess = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "throttle.access-timeout"); value.Exists() && value.Type == gjson.Number {
		data.ThrottleAccessTimeout = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "throttle.accounting"); value.Exists() && value.Type == gjson.Number {
		data.ThrottleAccounting = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "deadtime"); value.Exists() && value.Type == gjson.Number {
		data.Deadtime = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "dead-criteria.time"); value.Exists() && value.Type == gjson.Number {
		data.DeadCriteriaTime = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "dead-criteria.tries"); value.Exists() && value.Type == gjson.Number {
		data.DeadCriteriaTries = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "source-port.extended"); value.Exists() {
		data.SourcePortExtended = types.BoolValue(true)
	} else {
		data.SourcePortExtended = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "ipv4.dscp"); value.Exists() && value.Type == gjson.String {
		data.Ipv4Dscp = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "ipv6.dscp"); value.Exists() && value.Type == gjson.String {
		data.Ipv6Dscp = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "vsa.attribute.ignore.unknown"); value.Exists() {
		data.VsaAttributeIgnoreUnknown = types.BoolValue(true)
	} else {
		data.VsaAttributeIgnoreUnknown = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "disallow.null-username"); value.Exists() {
		data.DisallowNullUsername = types.BoolValue(true)
	} else {
		data.DisallowNullUsername = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "attribute.list"); value.Exists() {
		data.AttributeLists = make([]RadiusServerAttributeLists, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := RadiusServerAttributeLists{}
			if cValue := v.Get("list-name"); cValue.Exists() && cValue.Type == gjson.String {
				item.Name = types.StringValue(cValue.String())
			}
			if cValue := v.Get("attribute.radius-attributes"); cValue.Exists() && cValue.Type == gjson.String {
				item.RadiusAttributes = types.StringValue(cValue.String())
			}
			if cValue := v.Get("attribute.vendor-ids.vendor-id"); cValue.Exists() {
				item.AttributeVendorIds = make([]RadiusServerAttributeListsAttributeVendorIds, 0)
				cValue.ForEach(func(ck, cv gjson.Result) bool {
					cItem := RadiusServerAttributeListsAttributeVendorIds{}
					if ccValue := cv.Get("id"); ccValue.Exists() && ccValue.Type == gjson.Number {
						cItem.Id = types.Int64Value(ccValue.Int())
					}
					if ccValue := cv.Get("vendor-types.vendor-type"); ccValue.Exists() {
						cItem.VendorTypes = make([]RadiusServerAttributeListsAttributeVendorIdsVendorTypes, 0)
						ccValue.ForEach(func(cck, ccv gjson.Result) bool {
							ccItem := RadiusServerAttributeListsAttributeVendorIdsVendorTypes{}
							if cccValue := ccv.Get("vendor-type-id"); cccValue.Exists() && cccValue.Type == gjson.Number {
								ccItem.VendorTypeId = types.Int64Value(cccValue.Int())
							}
							cItem.VendorTypes = append(cItem.VendorTypes, ccItem)
							return true
						})
					}
					item.AttributeVendorIds = append(item.AttributeVendorIds, cItem)
					return true
				})
			}
			data.AttributeLists = append(data.AttributeLists, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "attribute.acct-session-id.prepend-nas-port-id"); value.Exists() {
		data.AttributeAcctSessionIdPrependNasPortId = types.BoolValue(true)
	} else {
		data.AttributeAcctSessionIdPrependNasPortId = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "attribute.acct-multi-session-id.include-parent-session-id"); value.Exists() {
		data.AttributeAcctMultiSessionIdIncludeParentSessionId = types.BoolValue(true)
	} else {
		data.AttributeAcctMultiSessionIdIncludeParentSessionId = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "attribute.filter-id-11.default.direction"); value.Exists() && value.Type == gjson.String {
		data.AttributeFilterId11DefaultDirection = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyData

func (data *RadiusServerData) fromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "hosts.host"); value.Exists() {
		data.Hosts = make([]RadiusServerHosts, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := RadiusServerHosts{}
			if cValue := v.Get("ordering-index"); cValue.Exists() && cValue.Type == gjson.Number {
				item.Order = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("address"); cValue.Exists() && cValue.Type == gjson.String {
				item.Address = types.StringValue(cValue.String())
			}
			if cValue := v.Get("auth-port"); cValue.Exists() && cValue.Type == gjson.Number {
				item.AuthPort = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("acct-port"); cValue.Exists() && cValue.Type == gjson.Number {
				item.AcctPort = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("timeout"); cValue.Exists() && cValue.Type == gjson.Number {
				item.Timeout = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("retransmit"); cValue.Exists() && cValue.Type == gjson.Number {
				item.Retransmit = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("test.username"); cValue.Exists() && cValue.Type == gjson.String {
				item.TestUsername = types.StringValue(cValue.String())
			}
			if cValue := v.Get("idle-time"); cValue.Exists() && cValue.Type == gjson.Number {
				item.IdleTime = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("ignore-auth-port"); cValue.Exists() {
				item.IgnoreAuthPort = types.BoolValue(true)
			} else {
				item.IgnoreAuthPort = types.BoolValue(false)
			}
			if cValue := v.Get("ignore-acct-port"); cValue.Exists() {
				item.IgnoreAcctPort = types.BoolValue(true)
			} else {
				item.IgnoreAcctPort = types.BoolValue(false)
			}
			if cValue := v.Get("dtls-server.trustpoint"); cValue.Exists() && cValue.Type == gjson.String {
				item.DtlsServerTrustpoint = types.StringValue(cValue.String())
			}
			if cValue := v.Get("radsec-server.trustpoint"); cValue.Exists() && cValue.Type == gjson.String {
				item.RadsecServerTrustpoint = types.StringValue(cValue.String())
			}
			data.Hosts = append(data.Hosts, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "timeout"); value.Exists() && value.Type == gjson.Number {
		data.Timeout = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "retransmit.retries"); value.Exists() && value.Type == gjson.Number {
		data.RetransmitRetries = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "retransmit.disable"); value.Exists() {
		data.RetransmitDisable = types.BoolValue(true)
	} else {
		data.RetransmitDisable = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "load-balance.method.least-outstanding.batch-size"); value.Exists() && value.Type == gjson.Number {
		data.LoadBalanceMethodLeastOutstandingBatchSize = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "load-balance.method.least-outstanding.ignore-preferred-server"); value.Exists() {
		data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer = types.BoolValue(true)
	} else {
		data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "throttle.access"); value.Exists() && value.Type == gjson.Number {
		data.ThrottleAccess = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "throttle.access-timeout"); value.Exists() && value.Type == gjson.Number {
		data.ThrottleAccessTimeout = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "throttle.accounting"); value.Exists() && value.Type == gjson.Number {
		data.ThrottleAccounting = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "deadtime"); value.Exists() && value.Type == gjson.Number {
		data.Deadtime = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "dead-criteria.time"); value.Exists() && value.Type == gjson.Number {
		data.DeadCriteriaTime = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "dead-criteria.tries"); value.Exists() && value.Type == gjson.Number {
		data.DeadCriteriaTries = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "source-port.extended"); value.Exists() {
		data.SourcePortExtended = types.BoolValue(true)
	} else {
		data.SourcePortExtended = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "ipv4.dscp"); value.Exists() && value.Type == gjson.String {
		data.Ipv4Dscp = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "ipv6.dscp"); value.Exists() && value.Type == gjson.String {
		data.Ipv6Dscp = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "vsa.attribute.ignore.unknown"); value.Exists() {
		data.VsaAttributeIgnoreUnknown = types.BoolValue(true)
	} else {
		data.VsaAttributeIgnoreUnknown = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "disallow.null-username"); value.Exists() {
		data.DisallowNullUsername = types.BoolValue(true)
	} else {
		data.DisallowNullUsername = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "attribute.list"); value.Exists() {
		data.AttributeLists = make([]RadiusServerAttributeLists, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := RadiusServerAttributeLists{}
			if cValue := v.Get("list-name"); cValue.Exists() && cValue.Type == gjson.String {
				item.Name = types.StringValue(cValue.String())
			}
			if cValue := v.Get("attribute.radius-attributes"); cValue.Exists() && cValue.Type == gjson.String {
				item.RadiusAttributes = types.StringValue(cValue.String())
			}
			if cValue := v.Get("attribute.vendor-ids.vendor-id"); cValue.Exists() {
				item.AttributeVendorIds = make([]RadiusServerAttributeListsAttributeVendorIds, 0)
				cValue.ForEach(func(ck, cv gjson.Result) bool {
					cItem := RadiusServerAttributeListsAttributeVendorIds{}
					if ccValue := cv.Get("id"); ccValue.Exists() && ccValue.Type == gjson.Number {
						cItem.Id = types.Int64Value(ccValue.Int())
					}
					if ccValue := cv.Get("vendor-types.vendor-type"); ccValue.Exists() {
						cItem.VendorTypes = make([]RadiusServerAttributeListsAttributeVendorIdsVendorTypes, 0)
						ccValue.ForEach(func(cck, ccv gjson.Result) bool {
							ccItem := RadiusServerAttributeListsAttributeVendorIdsVendorTypes{}
							if cccValue := ccv.Get("vendor-type-id"); cccValue.Exists() && cccValue.Type == gjson.Number {
								ccItem.VendorTypeId = types.Int64Value(cccValue.Int())
							}
							cItem.VendorTypes = append(cItem.VendorTypes, ccItem)
							return true
						})
					}
					item.AttributeVendorIds = append(item.AttributeVendorIds, cItem)
					return true
				})
			}
			data.AttributeLists = append(data.AttributeLists, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "attribute.acct-session-id.prepend-nas-port-id"); value.Exists() {
		data.AttributeAcctSessionIdPrependNasPortId = types.BoolValue(true)
	} else {
		data.AttributeAcctSessionIdPrependNasPortId = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "attribute.acct-multi-session-id.include-parent-session-id"); value.Exists() {
		data.AttributeAcctMultiSessionIdIncludeParentSessionId = types.BoolValue(true)
	} else {
		data.AttributeAcctMultiSessionIdIncludeParentSessionId = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "attribute.filter-id-11.default.direction"); value.Exists() && value.Type == gjson.String {
		data.AttributeFilterId11DefaultDirection = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyData

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletedItems

func (data *RadiusServer) getDeletedItems(ctx context.Context, state RadiusServer, version string) []string {
	deletedItems := make([]string, 0)
	if !state.AttributeFilterId11DefaultDirection.IsNull() && data.AttributeFilterId11DefaultDirection.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "attribute/filter-id-11/default/direction"))
	}
	if !state.AttributeAcctMultiSessionIdIncludeParentSessionId.IsNull() && data.AttributeAcctMultiSessionIdIncludeParentSessionId.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "attribute/acct-multi-session-id/include-parent-session-id"))
	}
	if !state.AttributeAcctSessionIdPrependNasPortId.IsNull() && data.AttributeAcctSessionIdPrependNasPortId.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "attribute/acct-session-id/prepend-nas-port-id"))
	}
	for i := range state.AttributeLists {
		keys := [...]string{"list-name"}
		stateKeyValues := [...]string{state.AttributeLists[i].Name.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + stateKeyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(state.AttributeLists[i].Name.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.AttributeLists {
			found = true
			if state.AttributeLists[i].Name.ValueString() != data.AttributeLists[j].Name.ValueString() {
				found = false
			}
			if found {
				for ci := range state.AttributeLists[i].AttributeVendorIds {
					ckeys := [...]string{"id"}
					cstateKeyValues := [...]string{strconv.FormatInt(state.AttributeLists[i].AttributeVendorIds[ci].Id.ValueInt64(), 10)}
					ckeyString := ""
					for cki := range ckeys {
						ckeyString += "[" + ckeys[cki] + "=" + cstateKeyValues[cki] + "]"
					}

					cemptyKeys := true
					if !reflect.ValueOf(state.AttributeLists[i].AttributeVendorIds[ci].Id.ValueInt64()).IsZero() {
						cemptyKeys = false
					}
					if cemptyKeys {
						continue
					}

					found := false
					for cj := range data.AttributeLists[j].AttributeVendorIds {
						found = true
						if state.AttributeLists[i].AttributeVendorIds[ci].Id.ValueInt64() != data.AttributeLists[j].AttributeVendorIds[cj].Id.ValueInt64() {
							found = false
						}
						if found {
							for cci := range state.AttributeLists[i].AttributeVendorIds[ci].VendorTypes {
								cckeys := [...]string{"vendor-type-id"}
								ccstateKeyValues := [...]string{strconv.FormatInt(state.AttributeLists[i].AttributeVendorIds[ci].VendorTypes[cci].VendorTypeId.ValueInt64(), 10)}
								cckeyString := ""
								for ccki := range cckeys {
									cckeyString += "[" + cckeys[ccki] + "=" + ccstateKeyValues[ccki] + "]"
								}

								ccemptyKeys := true
								if !reflect.ValueOf(state.AttributeLists[i].AttributeVendorIds[ci].VendorTypes[cci].VendorTypeId.ValueInt64()).IsZero() {
									ccemptyKeys = false
								}
								if ccemptyKeys {
									continue
								}

								found := false
								for ccj := range data.AttributeLists[j].AttributeVendorIds[cj].VendorTypes {
									found = true
									if state.AttributeLists[i].AttributeVendorIds[ci].VendorTypes[cci].VendorTypeId.ValueInt64() != data.AttributeLists[j].AttributeVendorIds[cj].VendorTypes[ccj].VendorTypeId.ValueInt64() {
										found = false
									}
									if found {
										break
									}
								}
								if !found {
									deletedItems = append(deletedItems, fmt.Sprintf("%v/%v%v/%v%v/%v%v", state.getPath(), "attribute/list", keyString, "attribute/vendor-ids/vendor-id", ckeyString, "vendor-types/vendor-type", cckeyString))
								}
							}
							break
						}
					}
					if !found {
						deletedItems = append(deletedItems, fmt.Sprintf("%v/%v%v/%v%v", state.getPath(), "attribute/list", keyString, "attribute/vendor-ids/vendor-id", ckeyString))
					}
				}
				if !state.AttributeLists[i].RadiusAttributes.IsNull() && data.AttributeLists[j].RadiusAttributes.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "attribute/list", keyString), "attribute/radius-attributes"))
				}
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, fmt.Sprintf("%v/%v%v", state.getPath(), "attribute/list", keyString))
		}
	}
	if !state.DisallowNullUsername.IsNull() && data.DisallowNullUsername.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "disallow/null-username"))
	}
	if !state.VsaAttributeIgnoreUnknown.IsNull() && data.VsaAttributeIgnoreUnknown.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "vsa/attribute/ignore/unknown"))
	}
	if !state.Ipv6Dscp.IsNull() && data.Ipv6Dscp.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "ipv6/dscp"))
	}
	if !state.Ipv4Dscp.IsNull() && data.Ipv4Dscp.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "ipv4/dscp"))
	}
	if !state.SourcePortExtended.IsNull() && data.SourcePortExtended.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "source-port/extended"))
	}
	if !state.DeadCriteriaTries.IsNull() && data.DeadCriteriaTries.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "dead-criteria/tries"))
	}
	if !state.DeadCriteriaTime.IsNull() && data.DeadCriteriaTime.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "dead-criteria/time"))
	}
	if !state.Deadtime.IsNull() && data.Deadtime.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "deadtime"))
	}
	if !state.ThrottleAccounting.IsNull() && data.ThrottleAccounting.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "throttle/accounting"))
	}
	if !state.ThrottleAccessTimeout.IsNull() && data.ThrottleAccessTimeout.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "throttle/access-timeout"))
	}
	if !state.ThrottleAccess.IsNull() && data.ThrottleAccess.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "throttle/access"))
	}
	if !state.LoadBalanceMethodLeastOutstandingIgnorePreferredServer.IsNull() && data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "load-balance/method/least-outstanding/ignore-preferred-server"))
	}
	if !state.LoadBalanceMethodLeastOutstandingBatchSize.IsNull() && data.LoadBalanceMethodLeastOutstandingBatchSize.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "load-balance/method/least-outstanding/batch-size"))
	}
	if !state.RetransmitDisable.IsNull() && data.RetransmitDisable.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "retransmit"))
	}
	if !state.RetransmitRetries.IsNull() && data.RetransmitRetries.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "retransmit"))
	}
	if !state.Timeout.IsNull() && data.Timeout.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "timeout"))
	}
	if !state.KeyType6.IsNull() && data.KeyType6.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "key/six"))
	}
	if !state.KeyType7.IsNull() && data.KeyType7.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "key/seven"))
	}
	for i := range state.Hosts {
		keys := [...]string{"ordering-index", "address", "auth-port", "acct-port"}
		stateKeyValues := [...]string{strconv.FormatInt(state.Hosts[i].Order.ValueInt64(), 10), state.Hosts[i].Address.ValueString(), strconv.FormatInt(state.Hosts[i].AuthPort.ValueInt64(), 10), strconv.FormatInt(state.Hosts[i].AcctPort.ValueInt64(), 10)}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + stateKeyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Hosts[i].Order.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(state.Hosts[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(state.Hosts[i].AuthPort.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(state.Hosts[i].AcctPort.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Hosts {
			found = true
			if state.Hosts[i].Order.ValueInt64() != data.Hosts[j].Order.ValueInt64() {
				found = false
			}
			if state.Hosts[i].Address.ValueString() != data.Hosts[j].Address.ValueString() {
				found = false
			}
			if state.Hosts[i].AuthPort.ValueInt64() != data.Hosts[j].AuthPort.ValueInt64() {
				found = false
			}
			if state.Hosts[i].AcctPort.ValueInt64() != data.Hosts[j].AcctPort.ValueInt64() {
				found = false
			}
			if found {
				if !state.Hosts[i].RadsecServerTrustpoint.IsNull() && data.Hosts[j].RadsecServerTrustpoint.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString), "radsec-server/trustpoint"))
				}
				if !state.Hosts[i].DtlsServerTrustpoint.IsNull() && data.Hosts[j].DtlsServerTrustpoint.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString), "dtls-server/trustpoint"))
				}
				if !state.Hosts[i].IgnoreAcctPort.IsNull() && data.Hosts[j].IgnoreAcctPort.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString), "ignore-acct-port"))
				}
				if !state.Hosts[i].IgnoreAuthPort.IsNull() && data.Hosts[j].IgnoreAuthPort.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString), "ignore-auth-port"))
				}
				if !state.Hosts[i].IdleTime.IsNull() && data.Hosts[j].IdleTime.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString), "idle-time"))
				}
				if !state.Hosts[i].TestUsername.IsNull() && data.Hosts[j].TestUsername.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString), "test/username"))
				}
				if !state.Hosts[i].KeyType6.IsNull() && data.Hosts[j].KeyType6.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString), "key/six"))
				}
				if !state.Hosts[i].KeyType7.IsNull() && data.Hosts[j].KeyType7.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString), "key/seven"))
				}
				if !state.Hosts[i].Retransmit.IsNull() && data.Hosts[j].Retransmit.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString), "retransmit"))
				}
				if !state.Hosts[i].Timeout.IsNull() && data.Hosts[j].Timeout.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString), "timeout"))
				}
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, fmt.Sprintf("%v/%v%v", state.getPath(), "hosts/host", keyString))
		}
	}
	return deletedItems
}

// End of section. //template:end getDeletedItems

// Section below is generated&owned by "gen/generator.go". //template:begin getEmptyLeafsDelete

func (data *RadiusServer) getEmptyLeafsDelete(ctx context.Context, version string) []string {
	emptyLeafsDelete := make([]string, 0)
	if !data.AttributeAcctMultiSessionIdIncludeParentSessionId.IsNull() && !data.AttributeAcctMultiSessionIdIncludeParentSessionId.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "attribute/acct-multi-session-id/include-parent-session-id"))
	}
	if !data.AttributeAcctSessionIdPrependNasPortId.IsNull() && !data.AttributeAcctSessionIdPrependNasPortId.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "attribute/acct-session-id/prepend-nas-port-id"))
	}
	for i := range data.AttributeLists {
		keys := [...]string{"list-name"}
		keyValues := [...]string{data.AttributeLists[i].Name.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
		for ci := range data.AttributeLists[i].AttributeVendorIds {
			ckeys := [...]string{"id"}
			ckeyValues := [...]string{strconv.FormatInt(data.AttributeLists[i].AttributeVendorIds[ci].Id.ValueInt64(), 10)}
			ckeyString := ""
			for cki := range ckeys {
				ckeyString += "[" + ckeys[cki] + "=" + ckeyValues[cki] + "]"
			}
			for cci := range data.AttributeLists[i].AttributeVendorIds[ci].VendorTypes {
				cckeys := [...]string{"vendor-type-id"}
				cckeyValues := [...]string{strconv.FormatInt(data.AttributeLists[i].AttributeVendorIds[ci].VendorTypes[cci].VendorTypeId.ValueInt64(), 10)}
				cckeyString := ""
				for ccki := range cckeys {
					cckeyString += "[" + cckeys[ccki] + "=" + cckeyValues[ccki] + "]"
				}
			}
		}
	}
	if !data.DisallowNullUsername.IsNull() && !data.DisallowNullUsername.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "disallow/null-username"))
	}
	if !data.VsaAttributeIgnoreUnknown.IsNull() && !data.VsaAttributeIgnoreUnknown.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "vsa/attribute/ignore/unknown"))
	}
	if !data.SourcePortExtended.IsNull() && !data.SourcePortExtended.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "source-port/extended"))
	}
	if !data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer.IsNull() && !data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "load-balance/method/least-outstanding/ignore-preferred-server"))
	}
	if !data.RetransmitDisable.IsNull() && !data.RetransmitDisable.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "retransmit"))
	}
	for i := range data.Hosts {
		keys := [...]string{"ordering-index", "address", "auth-port", "acct-port"}
		keyValues := [...]string{strconv.FormatInt(data.Hosts[i].Order.ValueInt64(), 10), data.Hosts[i].Address.ValueString(), strconv.FormatInt(data.Hosts[i].AuthPort.ValueInt64(), 10), strconv.FormatInt(data.Hosts[i].AcctPort.ValueInt64(), 10)}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
		if !data.Hosts[i].IgnoreAcctPort.IsNull() && !data.Hosts[i].IgnoreAcctPort.ValueBool() {
			emptyLeafsDelete = append(emptyLeafsDelete, path.Join(fmt.Sprintf("%v/%v%v", data.getPath(), "hosts/host", keyString), "ignore-acct-port"))
		}
		if !data.Hosts[i].IgnoreAuthPort.IsNull() && !data.Hosts[i].IgnoreAuthPort.ValueBool() {
			emptyLeafsDelete = append(emptyLeafsDelete, path.Join(fmt.Sprintf("%v/%v%v", data.getPath(), "hosts/host", keyString), "ignore-auth-port"))
		}
	}
	return emptyLeafsDelete
}

// End of section. //template:end getEmptyLeafsDelete

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletePaths
func (data *RadiusServer) getDeletePaths(ctx context.Context, version string) []string {
	var deletePaths []string
	if !data.AttributeFilterId11DefaultDirection.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "attribute/filter-id-11/default/direction"))
	}
	if !data.AttributeAcctMultiSessionIdIncludeParentSessionId.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "attribute/acct-multi-session-id/include-parent-session-id"))
	}
	if !data.AttributeAcctSessionIdPrependNasPortId.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "attribute/acct-session-id/prepend-nas-port-id"))
	}
	for i := range data.AttributeLists {
		keys := [...]string{"list-name"}
		keyValues := [...]string{data.AttributeLists[i].Name.ValueString()}

		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(data.AttributeLists[i].Name.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}
		deletePaths = append(deletePaths, fmt.Sprintf("%v/%v%v", data.getPath(), "attribute/list", keyString))
	}
	if !data.DisallowNullUsername.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "disallow/null-username"))
	}
	if !data.VsaAttributeIgnoreUnknown.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "vsa/attribute/ignore/unknown"))
	}
	if !data.Ipv6Dscp.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "ipv6/dscp"))
	}
	if !data.Ipv4Dscp.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "ipv4/dscp"))
	}
	if !data.SourcePortExtended.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "source-port/extended"))
	}
	if !data.DeadCriteriaTries.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "dead-criteria/tries"))
	}
	if !data.DeadCriteriaTime.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "dead-criteria/time"))
	}
	if !data.Deadtime.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "deadtime"))
	}
	if !data.ThrottleAccounting.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "throttle/accounting"))
	}
	if !data.ThrottleAccessTimeout.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "throttle/access-timeout"))
	}
	if !data.ThrottleAccess.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "throttle/access"))
	}
	if !data.LoadBalanceMethodLeastOutstandingIgnorePreferredServer.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "load-balance/method/least-outstanding/ignore-preferred-server"))
	}
	if !data.LoadBalanceMethodLeastOutstandingBatchSize.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "load-balance/method/least-outstanding/batch-size"))
	}
	if !data.RetransmitDisable.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "retransmit"))
	}
	if !data.RetransmitRetries.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "retransmit"))
	}
	if !data.Timeout.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "timeout"))
	}
	if !data.KeyType6.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "key/six"))
	}
	if !data.KeyType7.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "key/seven"))
	}
	for i := range data.Hosts {
		keys := [...]string{"ordering-index", "address", "auth-port", "acct-port"}
		keyValues := [...]string{strconv.FormatInt(data.Hosts[i].Order.ValueInt64(), 10), data.Hosts[i].Address.ValueString(), strconv.FormatInt(data.Hosts[i].AuthPort.ValueInt64(), 10), strconv.FormatInt(data.Hosts[i].AcctPort.ValueInt64(), 10)}

		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(data.Hosts[i].Order.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(data.Hosts[i].Address.ValueString()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(data.Hosts[i].AuthPort.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if !reflect.ValueOf(data.Hosts[i].AcctPort.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}
		deletePaths = append(deletePaths, fmt.Sprintf("%v/%v%v", data.getPath(), "hosts/host", keyString))
	}
	return deletePaths
}

// End of section. //template:end getDeletePaths
